// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TopUpDao is the data access object for table w_top_up.
type TopUpDao struct {
	table   string       // table is the underlying table name of the DAO.
	group   string       // group is the database configuration group name of current DAO.
	columns TopUpColumns // columns contains all the column names of Table for convenient usage.
}

// TopUpColumns defines and stores column names for table w_top_up.
type TopUpColumns struct {
	Id         string //
	Uid        string // 用户id
	TransId    string // 交易id
	Money      string //
	ChangeType string // 账变类型 最好配置与此表 u_wallet_change_type 中的相对应。 1 支付宝充值, 2 微信充值, 3 Paypal充值
	Ip         string // 用户操作ip
	Desc       string // 备注
	Status     string // 订单状态 1 等待, 2 成功, 3 失败
	Aid        string // 管理员id
	CreatedAt  string // 创建时间
	UpdatedAt  string // 修改时间
}

// topUpColumns holds the columns for table w_top_up.
var topUpColumns = TopUpColumns{
	Id:         "id",
	Uid:        "uid",
	TransId:    "trans_id",
	Money:      "money",
	ChangeType: "change_type",
	Ip:         "ip",
	Desc:       "desc",
	Status:     "status",
	Aid:        "aid",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

// NewTopUpDao creates and returns a new DAO object for table data access.
func NewTopUpDao() *TopUpDao {
	return &TopUpDao{
		group:   "sys",
		table:   "w_top_up",
		columns: topUpColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TopUpDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TopUpDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TopUpDao) Columns() TopUpColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TopUpDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TopUpDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TopUpDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
