### 用户注册
POST {{url}}/v1/user/register
Content-Type: application/json

{
  "uname": "test001",
  "pass": "a1231231"
}

> {%
    client.global.set("token", response.body.data.token);
%}

### 用户登录
POST {{url}}/v1/user/login
Content-Type: application/json
Lang: zh

{
  "uname": "test001",
  "pass": "a1231231"
}

> {%
    client.global.set("token", response.body.data.token);
%}

### 登录信息
GET {{url}}/v1/user/getUserInfo
Authorization: {{token}}

### 修改登录密码
PUT {{url}}/v1/user/pass
Authorization: {{token}}
Content-Type: application/json

{
  "oldPass": "a1231231",
  "pass": "a1231231"
}

### 修改昵称
PUT {{url}}/v1/user/nickname
Authorization: {{token}}
Content-Type: application/json

{
  "nickname": "ciel&33"
}

### 修改头像
PUT {{url}}/v1/user/icon
Authorization: {{token}}
Content-Type:  application/json

{
  "icon": "/icon/icon43.png"
}