### 创建充值订单
POST {{url}}/v1/wallet/topUp
Authorization: {{token}}
Content-Type: application/json

{
  "type": 1,
  "money": 10,
  "desc": "test"
}

### 查询充值订单
GET {{url}}/v1/wallet/listTopUp?page=1&size=10&status=3
Authorization: {{token}}

### 查询账变记录
GET {{url}}/v1/wallet/listChangeLog?page=1&size=10&type=
Authorization: {{token}}