// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TopUp is the golang structure of table w_top_up for DAO operations like Where/Data.
type TopUp struct {
	g.Meta     `orm:"table:w_top_up, do:true"`
	Id         interface{} //
	Uid        interface{} // 用户id
	TransId    interface{} // 交易id
	Money      interface{} //
	ChangeType interface{} // 账变类型 最好配置与此表 u_wallet_change_type 中的相对应。 1 支付宝充值, 2 微信充值, 3 Paypal充值
	Ip         interface{} // 用户操作ip
	Desc       interface{} // 备注
	Status     interface{} // 订单状态 1 等待, 2 成功, 3 失败
	Aid        interface{} // 管理员id
	CreatedAt  *gtime.Time // 创建时间
	UpdatedAt  *gtime.Time // 修改时间
}
