// =================================================================================
// This is auto-generated by FreeKey Admin at 2022-06-21 19:29:17. For more information please go to https://github.com/1211ciel/ciel-admin
// =================================================================================

package controller

import (
	"ciel-admin/internal/model/entity"
	"ciel-admin/internal/service/sys"
	"ciel-admin/manifest/config"
	"ciel-admin/utility/utils/res"
	"ciel-admin/utility/utils/xparam"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type cThingRecord struct{ *config.Search }

var ThingRecord = &cThingRecord{Search: &config.Search{
	T1: "f_thing_record", T2: "f_thing t2 on t1.tid = t2.id", OrderBy: "t1.id desc", SearchFields: "t1.*,t2.name",
	Fields: []*config.Field{
		{Name: "t2.name", SearchType: 2, QueryName: "name"},
		{Name: "desc", SearchType: 2, QueryName: "desc"},
		{Name: "tid", SearchType: 1, QueryName: "tid"},
	},
}}

func (c *cThingRecord) Path(r *ghttp.Request) {
	icon, err := sys.Icon(r.Context(), r.URL.Path)
	if err != nil {
		res.Err(err, r)
	}
	res.Page(r, "/f/f_thing_record.html", g.Map{"icon": icon})
}
func (c *cThingRecord) List(r *ghttp.Request) {
	page, size := res.GetPage(r)
	c.Page = page
	c.Size = size
	total, data, err := sys.List(r.Context(), c.Search)
	if err != nil {
		res.Err(err, r)
	}
	res.OkPage(page, size, total, data, r)
}
func (c *cThingRecord) GetById(r *ghttp.Request) {
	data, err := sys.GetById(r.Context(), c.T1, xparam.ID(r))
	if err != nil {
		res.Err(err, r)
	}
	res.OkData(data, r)
}
func (c *cThingRecord) Post(r *ghttp.Request) {
	d := entity.ThingRecord{}
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	if err := sys.Add(r.Context(), c.T1, &d); err != nil {
		res.Err(err, r)
	}
	res.Ok(r)
}
func (c *cThingRecord) Put(r *ghttp.Request) {
	d := entity.ThingRecord{}
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	if err := sys.Update(r.Context(), c.T1, d.Id, &d); err != nil {
		res.Err(err, r)
	}
	res.Ok(r)
}
func (c *cThingRecord) Del(r *ghttp.Request) {
	if err := sys.DelBatch(r.Context(), c.T1, r.Get("ids").Array()); err != nil {
		res.Err(err, r)
	}
	res.Ok(r)
}
