// =================================================================================
// This is auto-generated by FreeKey Admin at 2022-07-11 23:14:16. For more information see https://github.com/1211ciel/ciel-admin
// =================================================================================

package controller

import (
	"ciel-admin/internal/consts"
	"ciel-admin/internal/model/bo"
	"ciel-admin/internal/service/sys"
	"ciel-admin/utility/utils/res"
	"ciel-admin/utility/utils/xurl"
	"fmt"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type cAdminLoginLog struct{ bo.Search }

var AdminLoginLog = &cAdminLoginLog{Search: bo.Search{
	T1: "s_admin_login_log", T2: "s_admin t2 on t1.uid = t2.id ", OrderBy: "t1.id desc", SearchFields: "t1.*,t2.uname",
	Fields: []bo.Field{
		{Name: "t2.uname", SearchType: 2, QueryName: "adminLoginLog_uname"}, {Name: "ip", SearchType: 2, QueryName: "adminLoginLog_ip"},
	},
}}

func (c cAdminLoginLog) Path(r *ghttp.Request) {
	node, err := sys.NodeInfo(r.Context(), r.URL.Path)
	if err != nil {
		res.Err(err, r)
	}
	c.Page, c.Size = res.GetPage(r)
	total, data, err := sys.List(r.Context(), c.Search)
	if err != nil {
		res.Err(err, r)
	}
	if err = r.Response.WriteTpl("/sys/adminLoginLog/index.html", g.Map{
		"list": data,
		"page": r.GetPage(total, c.Size).GetContent(3),
		"node": node,
		"msg":  sys.MsgFromSession(r),
		"path": r.URL.Path,
	}); err != nil {
		res.Err(err, r)
	}
}

func (c cAdminLoginLog) Del(r *ghttp.Request) {
	id := r.Get("id")
	msg := fmt.Sprintf(consts.MsgPrimary, "删除成功")
	if err := sys.Del(r.Context(), c.T1, id); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/adminLoginLog/path?", xurl.ToUrlParams(r.GetQueryMap())))
}

func (c cAdminLoginLog) Clear(r *ghttp.Request) {

	msg := fmt.Sprintf(consts.MsgPrimary, "清理完成")
	if err := sys.ClearAdminLog(r.Context()); err != nil {
		msg = err.Error()
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/adminLoginLog/path?", xurl.ToUrlParams(r.GetQueryMap())))
}
