// =================================================================================
// This is auto-generated by FreeKey Admin at 2022-06-26 16:47:04. For more information see https://github.com/1211ciel/ciel-admin
// =================================================================================

package controller

import (

	"ciel-admin/internal/consts"
	"ciel-admin/internal/model/entity"
	"ciel-admin/internal/service/sys"
	"ciel-admin/manifest/config"
	"ciel-admin/utility/utils/res"
	"ciel-admin/utility/utils/xparam"
	"ciel-admin/utility/utils/xurl"
	"fmt"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type cDict struct{ *config.Search }

var Dict = &cDict{Search: &config.Search{
	T1:"s_dict", OrderBy: "t1.id desc", SearchFields: "t1.*",
	Fields: []*config.Field{
		{Name: "k", SearchType: 2, QueryName: "dict_k"}, {Name: "v", SearchType: 2, QueryName: "dict_v"}, {Name: "desc", SearchType: 2, QueryName: "dict_desc"}, {Name: "group", SearchType: 1, QueryName: "dict_group"}, {Name: "status", SearchType: 1, QueryName: "dict_status"}, {Name: "type", SearchType: 1, QueryName: "dict_type"}, 
	},
}}

func (c *cDict) Path(r *ghttp.Request) {
	node, err := sys.NodeInfo(r.Context(), r.URL.Path)
	if err != nil {
		res.Err(err, r)
	}
	c.Page, c.Size = res.GetPage(r)
	total, data, err := sys.List(r.Context(), c.Search)
	if err != nil {
		res.Err(err, r)
	}
	if err = r.Response.WriteTpl("/sys/dict/index.html", g.Map{
		"list": data,
		"page": r.GetPage(total, c.Size).GetContent(3),
		"node": node,
		"msg":  sys.MsgFromSession(r),
	}); err != nil {
		res.Err(err, r)
	}
}
func (c *cDict) PathAdd(r *ghttp.Request) {
	r.Response.WriteTpl("/sys/dict/add.html", g.Map{"msg": sys.MsgFromSession(r)})
}
func (c *cDict) Post(r *ghttp.Request) {
	d := entity.Dict{}
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	msg := fmt.Sprintf(consts.MsgPrimary, "添加成功")
	if err := sys.Add(r.Context(), c.T1, &d); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/dict/path/add?", xurl.ToUrlParams(r.GetQueryMap())))
}
func (c *cDict) Del(r *ghttp.Request) {
	id := r.Get("id")
	msg := fmt.Sprintf(consts.MsgPrimary, "删除成功")
	if err := sys.Del(r.Context(), c.T1, id); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/dict/path?", xurl.ToUrlParams(r.GetQueryMap())))
}
func (c *cDict) PathEdit(r *ghttp.Request) {
	data, err := sys.GetById(r.Context(), c.Search.T1, xparam.ID(r))
	if err != nil {
		res.Err(err, r)
	}
	_ = r.Session.Set("dict_edit", data.Map())
	_ = r.Response.WriteTpl("/sys/dict/edit.html", g.Map{"msg": sys.MsgFromSession(r)})
}
func (c *cDict) Put(r *ghttp.Request) {
	d := entity.Dict{}
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	if err := sys.Update(r.Context(), c.T1, d.Id, &d); err != nil {
		res.Err(err, r)
	}
	msg := fmt.Sprintf(consts.MsgPrimary, "修改成功")
	if err := sys.Update(r.Context(), c.T1, d.Id, &d); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/dict/path/edit/", d.Id, "?", xurl.ToUrlParams(r.GetQueryMap())))
}
