// =================================================================================
// This is auto-generated by FreeKey Admin at 2022-06-27 16:15:38. For more information see https://github.com/1211ciel/ciel-admin
// =================================================================================

package controller

import (

	"ciel-admin/internal/consts"
	"ciel-admin/internal/model/entity"
	"ciel-admin/internal/service/sys"
	"ciel-admin/manifest/config"
	"ciel-admin/utility/utils/res"
	"ciel-admin/utility/utils/xparam"
	"ciel-admin/utility/utils/xurl"
	"fmt"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type cOperationLog struct{ *config.Search }

var OperationLog = &cOperationLog{Search: &config.Search{
	T1:"s_operation_log",T2:"s_admin t2 on t1.uid = t2.id", OrderBy: "t1.id desc", SearchFields: "t1.*,t2.uname",
	Fields: []*config.Field{
		{Name: "t2.uname", SearchType: 2, QueryName: "operationLog_uname"}, {Name: "content", SearchType: 2, QueryName: "operationLog_content"}, 
	},
}}

func (c *cOperationLog) Path(r *ghttp.Request) {
	node, err := sys.NodeInfo(r.Context(), r.URL.Path)
	if err != nil {
		res.Err(err, r)
	}
	c.Page, c.Size = res.GetPage(r)
	total, data, err := sys.List(r.Context(), c.Search)
	if err != nil {
		res.Err(err, r)
	}
	if err = r.Response.WriteTpl("/sys/operationLog/index.html", g.Map{
		"list": data,
		"page": r.GetPage(total, c.Size).GetContent(3),
		"node": node,
		"msg":  sys.MsgFromSession(r),
	}); err != nil {
		res.Err(err, r)
	}
}
func (c *cOperationLog) PathAdd(r *ghttp.Request) {
	r.Response.WriteTpl("/sys/operationLog/add.html", g.Map{"msg": sys.MsgFromSession(r)})
}
func (c *cOperationLog) Post(r *ghttp.Request) {
	d := entity.OperationLog{}
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	msg := fmt.Sprintf(consts.MsgPrimary, "添加成功")
	if err := sys.Add(r.Context(), c.T1, &d); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/operationLog/path/add?", xurl.ToUrlParams(r.GetQueryMap())))
}
func (c *cOperationLog) Del(r *ghttp.Request) {
	id := r.Get("id")
	msg := fmt.Sprintf(consts.MsgPrimary, "删除成功")
	if err := sys.Del(r.Context(), c.T1, id); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/operationLog/path?", xurl.ToUrlParams(r.GetQueryMap())))
}
func (c *cOperationLog) PathEdit(r *ghttp.Request) {
	data, err := sys.GetById(r.Context(), c.Search.T1, xparam.ID(r))
	if err != nil {
		res.Err(err, r)
	}
	_ = r.Session.Set("operationLog_edit", data.Map())
	_ = r.Response.WriteTpl("/sys/operationLog/edit.html", g.Map{"msg": sys.MsgFromSession(r)})
}
func (c *cOperationLog) Put(r *ghttp.Request) {
	d := entity.OperationLog{}
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	if err := sys.Update(r.Context(), c.T1, d.Id, &d); err != nil {
		res.Err(err, r)
	}
	msg := fmt.Sprintf(consts.MsgPrimary, "修改成功")
	if err := sys.Update(r.Context(), c.T1, d.Id, &d); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/operationLog/path/edit/", d.Id, "?", xurl.ToUrlParams(r.GetQueryMap())))
}
