// =================================================================================
// This is auto-generated by FreeKey Admin at 2022-06-27 18:38:32. For more information see https://github.com/1211ciel/ciel-admin
// =================================================================================

package controller

import (
	"ciel-admin/internal/consts"
	"ciel-admin/internal/model/entity"
	"ciel-admin/internal/service/sys"
	"ciel-admin/manifest/config"
	"ciel-admin/utility/utils/res"
	"ciel-admin/utility/utils/xparam"
	"ciel-admin/utility/utils/xurl"
	"fmt"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type cRoleMenu struct{ *config.Search }

var RoleMenu = &cRoleMenu{Search: &config.Search{
	T1:           "s_role_menu",
	T2:           "s_role  t2 on t1.rid = t2.id",
	T3:           "s_menu t3 on t1.mid = t3.id",
	OrderBy:      "t1.id desc",
	SearchFields: "t1.*,t2.name role_name ,t3.name menu_name",
	Fields: []*config.Field{
		{Name: "rid", SearchType: 1},
	},
}}

func (c *cRoleMenu) Path(r *ghttp.Request) {
	node, err := sys.NodeInfo(r.Context(), r.URL.Path)
	if err != nil {
		res.Err(err, r)
	}
	node.Name = "角色菜单"
	node.Path = "/roleMenu/path"
	c.Page, c.Size = res.GetPage(r)
	total, data, err := sys.List(r.Context(), c.Search)
	if err != nil {
		res.Err(err, r)
	}
	if err = r.Response.WriteTpl("/sys/roleMenu/index.html", g.Map{
		"list": data,
		"page": r.GetPage(total, c.Size).GetContent(3),
		"node": node,
		"msg":  sys.MsgFromSession(r),
	}); err != nil {
		res.Err(err, r)
	}
}
func (c *cRoleMenu) PathAdd(r *ghttp.Request) {
	menus, err := sys.RoleNoMenu(r.Context(), r.Get("rid"))
	if err != nil {
		res.Err(err, r)
	}
	r.Response.WriteTpl("/sys/roleMenu/add.html", g.Map{"msg": sys.MsgFromSession(r), "menus": menus})
}
func (c *cRoleMenu) Post(r *ghttp.Request) {
	var d struct {
		Rid int
		Mid []int
	}
	_ = r.ParseForm(&d)
	msg := fmt.Sprintf(consts.MsgPrimary, "添加成功")
	if err := sys.AddRoleMenu(r.Context(), d.Rid, d.Mid); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/roleMenu/path/add?", xurl.ToUrlParams(r.GetQueryMap())))
}
func (c *cRoleMenu) Del(r *ghttp.Request) {
	id := r.Get("id")
	msg := fmt.Sprintf(consts.MsgPrimary, "删除成功")
	if err := sys.Del(r.Context(), c.T1, id); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/roleMenu/path?", xurl.ToUrlParams(r.GetQueryMap())))
}
func (c *cRoleMenu) PathEdit(r *ghttp.Request) {
	data, err := sys.GetById(r.Context(), c.Search.T1, xparam.ID(r))
	if err != nil {
		res.Err(err, r)
	}
	_ = r.Session.Set("roleMenu_edit", data.Map())
	_ = r.Response.WriteTpl("/sys/roleMenu/edit.html", g.Map{"msg": sys.MsgFromSession(r)})
}
func (c *cRoleMenu) Put(r *ghttp.Request) {
	d := entity.RoleMenu{}
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	if err := sys.Update(r.Context(), c.T1, d.Id, &d); err != nil {
		res.Err(err, r)
	}
	msg := fmt.Sprintf(consts.MsgPrimary, "修改成功")
	if err := sys.Update(r.Context(), c.T1, d.Id, &d); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/roleMenu/path/edit/", d.Id, "?", xurl.ToUrlParams(r.GetQueryMap())))
}
