// =================================================================================
// This is auto-generated by Freekey Admin at 2022-07-22 20:14:53. For more information see https://github.com/1211ciel/ciel-admin
// =================================================================================

package controller

import (
	"ciel-admin/internal/service/admin"
	"ciel-admin/internal/service/dict"
	"ciel-admin/internal/service/sys"
	"ciel-admin/internal/service/ws"
	"ciel-admin/utility/utils/res"
	"ciel-admin/utility/utils/xcaptcha"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/gogf/gf/v2/os/gctx"
	captcha "github.com/mojocn/base64Captcha"
)

type cBase struct {
	Table   string
	ReqPath string
	FileDir string
}

// ---Home----------------------------------------------------------------------
type home struct{}

var Home = &home{}

func (c home) IndexPage(r *ghttp.Request) {
	r.Response.RedirectTo(g.Config().MustGet(r.Context(), "home").String())
}

// ---System-----------------------------------------------------------------

type cSys struct{}

var Sys = &cSys{}

func (s cSys) GetDictByKey(r *ghttp.Request) {
	data, err := dict.GetByKey(r.Context(), r.Get("key").String())
	if err != nil {
		res.Err(err, r)
	}
	res.OkData(data, r)
}
func (s cSys) GetCaptcha(r *ghttp.Request) {
	var driver = xcaptcha.NewDriver().ConvertFonts()
	c := captcha.NewCaptcha(driver, xcaptcha.Store)
	_, content, answer := c.Driver.GenerateIdQuestionAnswer()
	id := r.GetQuery("id").String()
	item, _ := c.Driver.DrawCaptcha(content)
	c.Store.Set(id, answer)
	res.OkData(item.EncodeB64string(), r)
}
func (s cSys) Quotations(r *ghttp.Request) {
	node, err := sys.NodeInfo(r.Context(), "/to/quotations")
	if err != nil {
		res.Err(err, r)
	}
	if err = r.Response.WriteTpl("/sys/tool/quotations.html", g.Map{"node": node}); err != nil {
		res.Err(err, r)
	}
}
func (s cSys) DocumentIndex(r *ghttp.Request) {
	res.Tpl("/sys/tool/document.html", nil, r)
}

func (s cSys) RegisterRouter(g *ghttp.RouterGroup) {
	g.Group("/sys", func(g *ghttp.RouterGroup) {
		g.GET("/noticeAdmin", Ws.NoticeAdmin)
		g.GET("/document", s.DocumentIndex)
		g.Middleware(admin.AuthMiddleware)
		g.GET("/ws", Ws.GetAdminWs)
	})
}

// --- Ws ------------------------------------------------------------------------
type cWs struct{}

var Ws = &cWs{}

func (w cWs) GetUserWs(r *ghttp.Request) {
	ws.GetUserWs(r)
}
func (w cWs) GetAdminWs(r *ghttp.Request) {
	ws.GetAdminWs(r)
}
func (w cWs) NoticeUser(r *ghttp.Request) {
	var d struct {
		Uid     int `v:"required"`
		OrderId int `v:"required"`
	}
	err := r.Parse(&d)
	if err != nil {
		res.Err(err, r)
	}
	err = ws.NoticeUser(gctx.New(), d.Uid, d)
	if err != nil {
		res.Err(err, r)
	}
	res.Ok(r)
}
func (w cWs) NoticeAdmin(r *ghttp.Request) {
	var d struct {
		Msg string `v:"required" json:"msg"`
	}
	err := r.Parse(&d)
	if err != nil {
		res.Err(err, r)
	}
	err = ws.NoticeAllAdmin(r.Context(), d)
	if err != nil {
		res.Err(err, r)
	}
	res.Ok(r)
}
