// =================================================================================
// This is auto-generated by Freekey Admin at 2022-09-04 20:32:44. For more information see https://github.com/1211ciel/ciel-admin
// =================================================================================

package controller

import (
	"ciel-admin/internal/model/bo"
	"ciel-admin/internal/model/entity"
	"ciel-admin/internal/service/admin"
	"ciel-admin/internal/service/gold"
	"ciel-admin/internal/service/sys"
	"ciel-admin/internal/service/user"
	"ciel-admin/utility/utils/res"
	"ciel-admin/utility/utils/xparam"
	"ciel-admin/utility/utils/xurl"
	"fmt"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/gogf/gf/v2/util/gconv"
	"math"
)

type cGold struct{ cBase }

var Gold = cGold{cBase{"u_gold", "/admin/gold", "/user/gold"}}

func (c cGold) RegisterRouter(g *ghttp.RouterGroup) {
	g.Group("/gold", func(g *ghttp.RouterGroup) {
		g.Middleware(admin.AuthMiddleware)
		g.GET("/", c.Index)                 // 主页面
		g.GET("/edit/:id", c.EditIndex)     // 修改页面
		g.GET("/topUp/:id", c.TopUpIndex)   // 充值页面
		g.GET("/deduct/:id", c.DeductIndex) //扣除页面
		g.Middleware(admin.LockMiddleware, admin.ActionMiddleware)
		g.GET("/del/:id", c.Del) // 删除请求
		g.POST("/post", c.Post)  // 添加请求
		g.POST("/put", c.Put)    // 修改请求
		g.PUT("/updatePassByAdmin", c.UpdatePassByAdmin)
		g.POST("/topUpByAdmin", c.TopUpByAdmin)   // 充值金币
		g.POST("/deductByAdmin", c.DeductByAdmin) // 扣除用户金币
	})
}

func (c cGold) Index(r *ghttp.Request) {
	var (
		ctx     = r.Context()
		reqPath = r.URL.Path
		file    = fmt.Sprintf("%s/index.html", c.FileDir)
		msg     = sys.MsgFromSession(r)
		s       = bo.Search{
			T1:           c.Table,
			T2:           "u_user t2 on t1.uid = t2.id",
			SearchFields: "t1.*,t2.uname",
			OrderBy:      "t1.id desc", Fields: []bo.Field{
				{Name: "id", Type: 1},
				{Name: "status", Type: 1},
				{Name: "t2.uname", QueryName: "uname", Type: 2},
			}}
	)
	node, err := sys.NodeInfo(ctx, reqPath)
	if err != nil {
		res.Err(err, r)
	}
	s.Page, s.Size = res.GetPage(r)
	total, data, err := sys.List(ctx, s)
	if err != nil {
		res.Err(err, r)
	}
	// 返回页面
	res.Tpl(file, g.Map{
		"node": node,
		"list": data,
		"page": r.GetPage(total, s.Size).GetContent(3),
		"path": reqPath, // 用于确定导航菜单
		"msg":  msg,
	}, r)
}
func (c cGold) AddIndex(r *ghttp.Request) {
	res.Tpl(fmt.Sprint(c.FileDir, "/add.html"), g.Map{"msg": sys.MsgFromSession(r)}, r)
}
func (c cGold) EditIndex(r *ghttp.Request) {
	var (
		table = c.Table
		id    = xparam.ID(r)
		d     = g.Map{"msg": sys.MsgFromSession(r)}
		f     = fmt.Sprint(c.FileDir, "/edit.html")
	)
	data, err := sys.GetById(r.Context(), table, id)
	if err != nil {
		res.Err(err, r)
	}
	for k, v := range data.Map() {
		r.SetForm(k, v)
	}
	res.Tpl(f, d, r)
}
func (c cGold) TopUpIndex(r *ghttp.Request) {
	var (
		id  = r.Get("id").Uint64()
		ctx = r.Context()
	)
	userInfo, err := user.GetById(ctx, id)
	if err != nil {
		res.ErrSession(err, r)
	}
	goldInfo, err := gold.GetById(ctx, id)
	if err != nil {
		res.ErrSession(err, r)
	}
	res.Tpl("/user/gold/topUp.html", g.Map{
		"user":     userInfo,
		"goldInfo": goldInfo,
		"msg":      sys.MsgFromSession(r),
	}, r)
}

func (c cGold) DeductIndex(r *ghttp.Request) {
	var (
		id  = r.Get("id").Uint64()
		ctx = r.Context()
	)
	userInfo, err := user.GetById(ctx, id)
	if err != nil {
		res.ErrSession(err, r)
	}
	goldInfo, err := gold.GetById(ctx, id)
	if err != nil {
		res.ErrSession(err, r)
	}
	res.Tpl("/user/gold/deduct.html", g.Map{
		"user":     userInfo,
		"goldInfo": goldInfo,
		"msg":      sys.MsgFromSession(r),
	}, r)
}
func (c cGold) Post(r *ghttp.Request) {
	var (
		d = entity.Gold{}
	)
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	res.OkSession("添加成功", r)
	if err := sys.Add(r.Context(), c.Table, &d); err != nil {
		res.ErrSession(err, r)
	}
	path := fmt.Sprint(c.ReqPath, "/add?", xurl.ToUrlParams(r.GetQueryMap()))
	res.RedirectTo(path, r)
}
func (c cGold) Del(r *ghttp.Request) {
	var (
		id    = r.Get("id")
		table = c.Table
	)
	res.OkSession("删除成功", r)
	if err := sys.Del(r.Context(), table, id); err != nil {
		res.ErrSession(err, r)
	}
	path := fmt.Sprint(c.ReqPath, "?", xurl.ToUrlParams(r.GetQueryMap()))
	res.RedirectTo(path, r)
}
func (c cGold) Put(r *ghttp.Request) {
	var (
		d     = entity.Gold{}
		table = c.Table
	)
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	m := gconv.Map(d)
	delete(m, "createdAt")
	res.OkSession("修改成功", r)
	if err := sys.Update(r.Context(), table, d.Id, m); err != nil {
		res.ErrSession(err, r)
	}
	path := fmt.Sprint(c.ReqPath, "/edit/", d.Id, "?", xurl.ToUrlParams(r.GetQueryMap()))
	res.RedirectTo(path, r)
}

func (c cGold) UpdatePassByAdmin(r *ghttp.Request) {
	var (
		d struct {
			Uid  uint64
			Pass string
		}
		ctx = r.Context()
	)
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	if err := gold.UpdatePassByAdmin(ctx, d.Pass, d.Uid); err != nil {
		res.Err(err, r)
	}
	res.Ok(r)
}

func (c cGold) TopUpByAdmin(r *ghttp.Request) {
	var (
		d struct {
			Type int
			Uid  uint64
			Gold float64
			Desc string
		}
		ctx = r.Context()
	)
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	res.OkSession("充值成功", r)
	if err := gold.TopUpByAdmin(ctx, d.Type, d.Uid, d.Gold, d.Desc); err != nil {
		res.ErrSession(err, r)
	}
	path := fmt.Sprintf("/admin/gold/topUp/%d?%s", d.Uid, xurl.ToUrlParams(r.GetQueryMap()))
	res.RedirectTo(path, r)
}

func (c cGold) DeductByAdmin(r *ghttp.Request) {
	var (
		d struct {
			Type   int
			Uid    uint64
			Amount float64
		}
		ctx  = r.Context()
		path = fmt.Sprintf("/admin/gold/deduct/%d?%s", r.GetForm("uid").Uint64(), xurl.ToUrlParams(r.GetQueryMap()))
	)
	res.OkSession("扣除成功", r)
	if err := r.Parse(&d); err != nil {
		res.ErrSession(err, r)
		goto here
	}
	if err := gold.DeductByAdmin(ctx, d.Type, d.Uid, math.Abs(d.Amount)*-1); err != nil {
		res.ErrSession(err, r)
	}
here:
	res.RedirectTo(path, r)
}
