// =================================================================================
// This is auto-generated by FreeKey Admin at 2022-07-19 16:15:27. For more information see https://github.com/1211ciel/ciel-admin
// =================================================================================

package controller

import (

	"ciel-admin/internal/consts"
	"ciel-admin/internal/model/bo"
	"ciel-admin/internal/model/entity"
	"ciel-admin/internal/service/sys"
	"ciel-admin/utility/utils/res"
	"ciel-admin/utility/utils/xparam"
	"ciel-admin/utility/utils/xurl"
	"fmt"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/gogf/gf/v2/util/gconv"
)

type cUser struct{ bo.Search }

var User = &cUser{Search: bo.Search{
	T1:"u_user",T2:"u_user_login_log t2 on t2.uid = t1.id", OrderBy: "t1.id desc", SearchFields: "t1.*,t2.ip",
	Fields: []bo.Field{
		{Name: "uname", SearchType: 2, QueryName: "user_uname"}, {Name: "t2.ip", SearchType: 2, QueryName: "user_ip"}, {Name: "status", SearchType: 2, QueryName: "user_status"}, 
	},
}}

func (c cUser) Path(r *ghttp.Request) {
	node, err := sys.NodeInfo(r.Context(), r.URL.Path)
	if err != nil {
		res.Err(err, r)
	}
	c.Page, c.Size = res.GetPage(r)
	total, data, err := sys.List(r.Context(), c.Search)
	if err != nil {
		res.Err(err, r)
	}
	if err = r.Response.WriteTpl("/user/user/index.html", g.Map{
		"list": data,
		"page": r.GetPage(total, c.Size).GetContent(3),
		"node": node,
		"msg":  sys.MsgFromSession(r),
		"path": r.URL.Path,
	}); err != nil {
		res.Err(err, r)
	}
}
func (c cUser) PathAdd(r *ghttp.Request) {
	r.Response.WriteTpl("/user/user/add.html", g.Map{"msg": sys.MsgFromSession(r)})
}
func (c cUser) Post(r *ghttp.Request) {
	d := entity.User{}
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	msg := fmt.Sprintf(consts.MsgPrimary, "添加成功")
	if err := sys.Add(r.Context(), c.T1, &d); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/user/path/add?", xurl.ToUrlParams(r.GetQueryMap())))
}
func (c cUser) Del(r *ghttp.Request) {
	id := r.Get("id")
	msg := fmt.Sprintf(consts.MsgPrimary, "删除成功")
	if err := sys.Del(r.Context(), c.T1, id); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/user/path?", xurl.ToUrlParams(r.GetQueryMap())))
}
func (c cUser) PathEdit(r *ghttp.Request) {
	data, err := sys.GetById(r.Context(), c.Search.T1, xparam.ID(r))
	if err != nil {
		res.Err(err, r)
	}
	_ = r.Session.Set("user_edit", data.Map())
	_ = r.Response.WriteTpl("/user/user/edit.html", g.Map{"msg": sys.MsgFromSession(r)})
}
func (c cUser) Put(r *ghttp.Request) {
	d := entity.User{}
	if err := r.Parse(&d); err != nil {
		res.Err(err, r)
	}
	m := gconv.Map(d)
	delete(m, "createdAt")
	msg := fmt.Sprintf(consts.MsgPrimary, "修改成功")
	if err := sys.Update(r.Context(), c.T1, d.Id, m); err != nil {
		msg = fmt.Sprintf(consts.MsgWarning, err.Error())
	}
	_ = r.Session.Set("msg", msg)
	r.Response.RedirectTo(fmt.Sprint("/user/path/edit/", d.Id, "?", xurl.ToUrlParams(r.GetQueryMap())))
}
