// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminLoginLog is the golang structure of table s_admin_login_log for DAO operations like Where/Data.
type AdminLoginLog struct {
	g.Meta    `orm:"table:s_admin_login_log, do:true"`
	Id        interface{} //
	Uid       interface{} // {"label":"用户id","searchType":1,"hide":1,"disabled":1,"required":1}
	Ip        interface{} // {"label":"登录IP","notShow":0,"fieldType":"text","editHide":0,"editDisabled":0,"required":1}
	Area      interface{} // {"searchType":2,"hide":1}
	Status    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
