// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Api is the golang structure of table s_api for DAO operations like Where/Data.
type Api struct {
	g.Meta    `orm:"table:s_api, do:true"`
	Id        interface{} //
	Url       interface{} //
	Method    interface{} //
	Group     interface{} //
	Type      interface{} // 类型 1添加 2删除 3修改 4查看 5 页面
	Desc      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
