// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BookWriter is the golang structure of table b_book_writer for DAO operations like Where/Data.
type BookWriter struct {
	g.Meta    `orm:"table:b_book_writer, do:true"`
	Id        interface{} //
	Name      interface{} //
	Desc      interface{} //
	Year      interface{} //
	Status    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
