// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Book is the golang structure of table b_book for DAO operations like Where/Data.
type Book struct {
	g.Meta          `orm:"table:b_book, do:true"`
	Id              interface{} //
	Name            interface{} //
	Writer          interface{} //
	Category        interface{} //
	Icon            interface{} //
	Poster          interface{} //
	Year            interface{} //
	YearStatus      interface{} // 1准确，2大概
	Keywords        interface{} //
	Description     interface{} //
	ShortDesc       interface{} //
	Summary         interface{} // 简介
	Quotations      interface{} // 名言
	RelationBooks   interface{} //
	Visit           interface{} //
	Sort            interface{} //
	RecommendStatus interface{} // 是否推荐 1是 2否
	Status          interface{} //
	KnowledgeStatus interface{} //
	CreatedAt       *gtime.Time //
	UpdatedAt       *gtime.Time //
}
