// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BookChapter is the golang structure of table b_book_chapter for DAO operations like Where/Data.
type BookChapter struct {
	g.Meta        `orm:"table:b_book_chapter, do:true"`
	Id            interface{} //
	BookId        interface{} //
	Title         interface{} //
	Sort          interface{} //
	Desc          interface{} //
	Visit         interface{} //
	Content       interface{} //
	ContentLength interface{} // 正文字符数
	Status        interface{} //
	Keywords      interface{} //
	Last          interface{} //
	Next          interface{} //
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
