// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// BookCategory is the golang structure of table b_book_category for DAO operations like Where/Data.
type BookCategory struct {
	g.Meta  `orm:"table:b_book_category, do:true"`
	Id      interface{} //
	Name    interface{} //
	Icon    interface{} //
	Poster  interface{} //
	Speak   interface{} //
	Mark    interface{} //
	Desc    interface{} //
	BookNum interface{} //
	Sort    interface{} //
	Status  interface{} //
}
