// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// EnDocumentParagraphUser is the golang structure of table e_en_document_paragraph_user for DAO operations like Where/Data.
type EnDocumentParagraphUser struct {
	g.Meta      `orm:"table:e_en_document_paragraph_user, do:true"`
	Id          interface{} //
	ParagraphId interface{} //
	Uid         interface{} //
	Level       interface{} //
	Progress    interface{} //
}
