// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EnDocumentParagraphWordUser is the golang structure of table e_en_document_paragraph_word_user for DAO operations like Where/Data.
type EnDocumentParagraphWordUser struct {
	g.Meta     `orm:"table:e_en_document_paragraph_word_user, do:true"`
	Id         interface{} //
	WordId     interface{} //
	Uid        interface{} //
	Level      interface{} //
	Count      interface{} //
	StudyDate  *gtime.Time //
	HasBeenAdd interface{} //
}
