// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// EnDocumentUser is the golang structure of table e_en_document_user for DAO operations like Where/Data.
type EnDocumentUser struct {
	g.Meta     `orm:"table:e_en_document_user, do:true"`
	Id         interface{} //
	DocumentId interface{} //
	Uid        interface{} //
	Level      interface{} //
}
