// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// EnDocumentParagraph is the golang structure of table e_en_document_paragraph for DAO operations like Where/Data.
type EnDocumentParagraph struct {
	g.Meta     `orm:"table:e_en_document_paragraph, do:true"`
	Id         interface{} //
	DocumentId interface{} //
	H2         interface{} //
	H3         interface{} //
	WordNum    interface{} //
	Content    interface{} //
}
