// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// EnDocumentParagraphWord is the golang structure of table e_en_document_paragraph_word for DAO operations like Where/Data.
type EnDocumentParagraphWord struct {
	g.Meta      `orm:"table:e_en_document_paragraph_word, do:true"`
	Id          interface{} //
	ParagraphId interface{} //
	En          interface{} //
	Zh          interface{} //
	Sentence    interface{} //
	SentenceZh  interface{} //
}
