// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EnPracticeWord is the golang structure of table e_en_practice_word for DAO operations like Where/Data.
type EnPracticeWord struct {
	g.Meta     `orm:"table:e_en_practice_word, do:true"`
	Id         interface{} //
	Group      interface{} //
	Uid        interface{} //
	En         interface{} //
	Zh         interface{} //
	Sentence   interface{} //
	SentenceZh interface{} //
	Count      interface{} //
	Level      interface{} // 1单词粉末 2单词碎片 3单词 4小单词 5大单词 6硕大的单词 7闪光的单词 8燃烧的单词 9灿烂的单词
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
}
