// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// EnPracticeWordCount is the golang structure of table e_en_practice_word_count for DAO operations like Where/Data.
type EnPracticeWordCount struct {
	g.Meta  `orm:"table:e_en_practice_word_count, do:true"`
	Id      interface{} //
	Uid     interface{} //
	Level1  interface{} //
	Level2  interface{} //
	Level3  interface{} //
	Level4  interface{} //
	Level5  interface{} //
	Level6  interface{} //
	Level7  interface{} //
	Level8  interface{} //
	Level9  interface{} //
	Level10 interface{} //
}
