// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// EnUserWord is the golang structure of table e_en_user_word for DAO operations like Where/Data.
type EnUserWord struct {
g.Meta `orm:"table:e_en_user_word, do:true"`
    Uid interface{} //   
    Word interface{} //   
    CreatedAt *gtime.Time //   
}