// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// EnWordStudyLog is the golang structure of table e_en_word_study_log for DAO operations like Where/Data.
type EnWordStudyLog struct {
	g.Meta      `orm:"table:e_en_word_study_log, do:true"`
	Uid         interface{} //
	CreatedDate *gtime.Time //
	Num         interface{} //
}
