// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Event is the golang structure of table e_event for DAO operations like Where/Data.
type Event struct {
	g.Meta    `orm:"table:e_event, do:true"`
	Id        interface{} //
	Year      interface{} //
	Month     interface{} //
	Day       interface{} //
	Category1 interface{} //
	Category2 interface{} //
	Tag       interface{} //
	Event     interface{} //
	Summery   interface{} //
	Status    interface{} //
	About     interface{} //
	CreatedAt *gtime.Time //
}
