// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FreeKeyVisitLog is the golang structure of table f_free_key_visit_log for DAO operations like Where/Data.
type FreeKeyVisitLog struct {
	g.Meta    `orm:"table:f_free_key_visit_log, do:true"`
	Id        interface{} //
	Visit     interface{} //
	Max       interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
