// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Knowledge is the golang structure of table k_knowledge for DAO operations like Where/Data.
type Knowledge struct {
	g.Meta    `orm:"table:k_knowledge, do:true"`
	Id        interface{} //
	Name      interface{} //
	Content   interface{} //
	Status    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
