// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// QuestionCategory is the golang structure of table q_question_category for DAO operations like Where/Data.
type QuestionCategory struct {
	g.Meta `orm:"table:q_question_category, do:true"`
	Id     interface{} //
	Name   interface{} //
	Icon   interface{} //
	Desc   interface{} //
	Sort   interface{} //
	Num    interface{} // article num
	Status interface{} //
}
