// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Question is the golang structure of table q_question for DAO operations like Where/Data.
type Question struct {
	g.Meta    `orm:"table:q_question, do:true"`
	Id        interface{} //
	Question  interface{} //
	Category  interface{} //
	Desc      interface{} //
	Icon      interface{} //
	EnContent interface{} //
	Visit     interface{} //
	Status    interface{} //
	CreatedAt *gtime.Time //
}
