// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Quotations is the golang structure of table q_quotations for DAO operations like Where/Data.
type Quotations struct {
	g.Meta    `orm:"table:q_quotations, do:true"`
	Id        interface{} //
	Book      interface{} // 书籍名称
	Writer    interface{} // 作者名称
	Category  interface{} // 类型
	Content   interface{} //
	ContentEn interface{} //
	Like      interface{} // 喜欢的次数
	Status    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
