// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Read is the golang structure of table r_read for DAO operations like Where/Data.
type Read struct {
	g.Meta      `orm:"table:r_read, do:true"`
	Id          interface{} //
	Category1   interface{} //
	Category2   interface{} //
	Tag         interface{} //
	Title       interface{} //
	Icon        interface{} //
	Poster      interface{} //
	Visit       interface{} //
	Keywords    interface{} //
	Writer      interface{} //
	Description interface{} //
	Content     interface{} //
	Status      interface{} //
	Sort        interface{} //
	Recommend   interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
