// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// RelationLink is the golang structure of table k_relation_link for DAO operations like Where/Data.
type RelationLink struct {
	g.Meta    `orm:"table:k_relation_link, do:true"`
	Id        interface{} //
	Category  interface{} //
	Name      interface{} //
	Link      interface{} //
	Summery   interface{} //
	Desc      interface{} //
	Sort      interface{} //
	CreatedAt *gtime.Time //
}
