// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// TopUpCategory is the golang structure of table u_top_up_category for DAO operations like Where/Data.
type TopUpCategory struct {
	g.Meta   `orm:"table:u_top_up_category, do:true"`
	Id       interface{} //
	Title    interface{} //
	SubTitle interface{} //
	Type     interface{} //
	Summary  interface{} //
	Desc     interface{} //
	Status   interface{} //
}
