// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UUserStudyStatus is the golang structure of table u_user_study_status for DAO operations like Where/Data.
type UUserStudyStatus struct {
	g.Meta                `orm:"table:u_user_study_status, do:true"`
	Id                    interface{} //
	Uid                   interface{} //
	WordNum               interface{} // 单词学习个数
	PersistInLearningDays interface{} // 坚持学习天数
	LastLearningDate      *gtime.Time // 上次学习日期
	RedHardNum            interface{} // 小红心个数
}
