// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WalletStatisticsLog is the golang structure of table u_wallet_statistics_log for DAO operations like Where/Data.
type WalletStatisticsLog struct {
	g.Meta      `orm:"table:u_wallet_statistics_log, do:true"`
	Id          interface{} //
	Uid         interface{} //
	T1          interface{} //
	T2          interface{} //
	T3          interface{} //
	T4          interface{} //
	T5          interface{} //
	T6          interface{} //
	T7          interface{} //
	T8          interface{} //
	T9          interface{} //
	T10         interface{} //
	T11         interface{} //
	T12         interface{} //
	T13         interface{} //
	CreatedDate *gtime.Time //
}
