package cmd

import (
	"ciel-admin/internal/controller"
	"ciel-admin/internal/service/sys"
	"github.com/gogf/gf/v2/net/ghttp"
)

func registerGenFileRouter(s *ghttp.Server) {
	s.Group("/menu", func(g *ghttp.RouterGroup) {
		g.Middleware(sys.AuthAdmin)
		g.GET("/path", controller.Menu.Path)
		g.GET("/path/add", controller.Menu.PathAdd)
		g.GET("/path/edit/:id", controller.Menu.PathEdit)
		g.GET("/level1", controller.Sys.Level1)
		g.Middleware(sys.LockAction)
		g.GET("/path/del/:id", controller.Menu.Del)
		g.POST("/post", controller.Menu.Post)
		g.POST("/put", controller.Menu.Put)
	})
	s.Group("/api", func(g *ghttp.RouterGroup) {
		g.Middleware(sys.AuthAdmin)
		g.GET("/path", controller.Api.Path)
		g.GET("/path/add", controller.Api.PathAdd)
		g.GET("/path/edit/:id", controller.Api.PathEdit)
		g.Middleware(sys.LockAction)
		g.GET("/path/del/:id", controller.Api.Del)
		g.POST("/post", controller.Api.Post)
		g.POST("/put", controller.Api.Put)
	})
	s.Group("/dict", func(g *ghttp.RouterGroup) {
		g.Middleware(sys.AuthAdmin)
		g.GET("/path", controller.Dict.Path)
		g.GET("/path/add", controller.Dict.PathAdd)
		g.GET("/path/edit/:id", controller.Dict.PathEdit)
		g.Middleware(sys.LockAction)
		g.GET("/path/del/:id", controller.Dict.Del)
		g.POST("/post", controller.Dict.Post)
		g.POST("/put", controller.Dict.Put)
	})
	s.Group("/operationLog", func(g *ghttp.RouterGroup) {
		g.Middleware(sys.AuthAdmin)
		g.GET("/path", controller.OperationLog.Path)
		g.GET("/path/add", controller.OperationLog.PathAdd)
		g.GET("/path/edit/:id", controller.OperationLog.PathEdit)
		g.Middleware(sys.LockAction)
		g.GET("/path/del/:id", controller.OperationLog.Del)
		g.POST("/post", controller.OperationLog.Post)
		g.POST("/put", controller.OperationLog.Put)
	})
	s.Group("/admin", func(g *ghttp.RouterGroup) {
		g.Middleware(sys.AuthAdmin)
		g.GET("/path", controller.Admin.Path)
		g.GET("/path/add", controller.Admin.PathAdd)
		g.GET("/path/edit/:id", controller.Admin.PathEdit)
		g.Middleware(sys.LockAction)
		g.GET("/path/del/:id", controller.Admin.Del)
		g.POST("/post", controller.Admin.Post)
		g.POST("/put", controller.Admin.Put)
	})
	s.Group("/role", func(g *ghttp.RouterGroup) {
		g.Middleware(sys.AuthAdmin)
		g.GET("/path", controller.Role.Path)
		g.GET("/path/add", controller.Role.PathAdd)
		g.GET("/path/edit/:id", controller.Role.PathEdit)
		g.Middleware(sys.LockAction)
		g.GET("/path/del/:id", controller.Role.Del)
		g.POST("/post", controller.Role.Post)
		g.POST("/put", controller.Role.Put)
	})
	s.Group("/roleMenu", func(g *ghttp.RouterGroup) {
		g.Middleware(sys.AuthAdmin)
		g.GET("/path", controller.RoleMenu.Path)
		g.GET("/path/add", controller.RoleMenu.PathAdd)
		g.GET("/path/edit/:id", controller.RoleMenu.PathEdit)
		g.Middleware(sys.LockAction)
		g.GET("/path/del/:id", controller.RoleMenu.Del)
		g.POST("/post", controller.RoleMenu.Post)
		g.POST("/put", controller.RoleMenu.Put)
	})
	s.Group("/roleApi", func(g *ghttp.RouterGroup) {
		g.Middleware(sys.AuthAdmin)
		g.GET("/path", controller.RoleApi.Path)
		g.GET("/path/add", controller.RoleApi.PathAdd)
		g.GET("/path/edit/:id", controller.RoleApi.PathEdit)
		g.Middleware(sys.LockAction)
		g.GET("/path/del/:id", controller.RoleApi.Del)
		g.GET("/clear/:rid", controller.RoleApi.Clear)
		g.POST("/post", controller.RoleApi.Post)
		g.POST("/put", controller.RoleApi.Put)
	})
	s.Group("/file", func(g *ghttp.RouterGroup) {
		g.Middleware(sys.AuthAdmin)
		g.GET("/path", controller.File.Path)
		g.GET("/path/add", controller.File.PathAdd)
		g.GET("/path/edit/:id", controller.File.PathEdit)
		g.Middleware(sys.LockAction)
		g.GET("/path/del/:id", controller.File.Del)
		g.POST("/post", controller.File.Post)
		g.POST("/put", controller.File.Put)
		g.POST("/upload", controller.File.Upload)
	})
}
