// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TopUp is the golang structure for table top_up.
type TopUp struct {
	Id         uint64      `json:"id"         description:""`
	Uid        uint64      `json:"uid"        description:"用户id"`
	TransId    string      `json:"transId"    description:"交易id"`
	Money      float64     `json:"money"      description:""`
	ChangeType uint        `json:"changeType" description:"账变类型 最好配置与此表 u_wallet_change_type 中的相对应。 1 支付宝充值, 2 微信充值, 3 Paypal充值"`
	Ip         string      `json:"ip"         description:"用户操作ip"`
	Desc       string      `json:"desc"       description:"备注"`
	Status     uint        `json:"status"     description:"订单状态 1 等待, 2 成功, 3 失败"`
	Aid        uint64      `json:"aid"        description:"管理员id"`
	CreatedAt  *gtime.Time `json:"createdAt"  description:"创建时间"`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:"修改时间"`
}
