// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BookWriterDao is the data access object for table b_book_writer.
type BookWriterDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns BookWriterColumns // columns contains all the column names of Table for convenient usage.
}

// BookWriterColumns defines and stores column names for table b_book_writer.
type BookWriterColumns struct {
	Id        string //
	Name      string //
	Desc      string //
	Year      string //
	Status    string //
	CreatedAt string //
	UpdatedAt string //
}

// bookWriterColumns holds the columns for table b_book_writer.
var bookWriterColumns = BookWriterColumns{
	Id:        "id",
	Name:      "name",
	Desc:      "desc",
	Year:      "year",
	Status:    "status",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewBookWriterDao creates and returns a new DAO object for table data access.
func NewBookWriterDao() *BookWriterDao {
	return &BookWriterDao{
		group:   "default",
		table:   "b_book_writer",
		columns: bookWriterColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BookWriterDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BookWriterDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BookWriterDao) Columns() BookWriterColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BookWriterDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BookWriterDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BookWriterDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
