// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// EnDocumentParagraphWordDao is the data access object for table e_en_document_paragraph_word.
type EnDocumentParagraphWordDao struct {
	table   string                         // table is the underlying table name of the DAO.
	group   string                         // group is the database configuration group name of current DAO.
	columns EnDocumentParagraphWordColumns // columns contains all the column names of Table for convenient usage.
}

// EnDocumentParagraphWordColumns defines and stores column names for table e_en_document_paragraph_word.
type EnDocumentParagraphWordColumns struct {
	Id          string //
	ParagraphId string //
	En          string //
	Zh          string //
	Sentence    string //
	SentenceZh  string //
}

// enDocumentParagraphWordColumns holds the columns for table e_en_document_paragraph_word.
var enDocumentParagraphWordColumns = EnDocumentParagraphWordColumns{
	Id:          "id",
	ParagraphId: "paragraph_id",
	En:          "en",
	Zh:          "zh",
	Sentence:    "sentence",
	SentenceZh:  "sentence_zh",
}

// NewEnDocumentParagraphWordDao creates and returns a new DAO object for table data access.
func NewEnDocumentParagraphWordDao() *EnDocumentParagraphWordDao {
	return &EnDocumentParagraphWordDao{
		group:   "default",
		table:   "e_en_document_paragraph_word",
		columns: enDocumentParagraphWordColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *EnDocumentParagraphWordDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *EnDocumentParagraphWordDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *EnDocumentParagraphWordDao) Columns() EnDocumentParagraphWordColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *EnDocumentParagraphWordDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *EnDocumentParagraphWordDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *EnDocumentParagraphWordDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
