// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// EnDocumentUserDao is the data access object for table e_en_document_user.
type EnDocumentUserDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns EnDocumentUserColumns // columns contains all the column names of Table for convenient usage.
}

// EnDocumentUserColumns defines and stores column names for table e_en_document_user.
type EnDocumentUserColumns struct {
	Id         string //
	DocumentId string //
	Uid        string //
	Level      string //
}

// enDocumentUserColumns holds the columns for table e_en_document_user.
var enDocumentUserColumns = EnDocumentUserColumns{
	Id:         "id",
	DocumentId: "document_id",
	Uid:        "uid",
	Level:      "level",
}

// NewEnDocumentUserDao creates and returns a new DAO object for table data access.
func NewEnDocumentUserDao() *EnDocumentUserDao {
	return &EnDocumentUserDao{
		group:   "default",
		table:   "e_en_document_user",
		columns: enDocumentUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *EnDocumentUserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *EnDocumentUserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *EnDocumentUserDao) Columns() EnDocumentUserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *EnDocumentUserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *EnDocumentUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *EnDocumentUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
