// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// EnPracticeWordDao is the data access object for table e_en_practice_word.
type EnPracticeWordDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns EnPracticeWordColumns // columns contains all the column names of Table for convenient usage.
}

// EnPracticeWordColumns defines and stores column names for table e_en_practice_word.
type EnPracticeWordColumns struct {
	Id         string //
	Group      string //
	Uid        string //
	En         string //
	Zh         string //
	Sentence   string //
	SentenceZh string //
	Count      string //
	Level      string // 1单词粉末 2单词碎片 3单词 4小单词 5大单词 6硕大的单词 7闪光的单词 8燃烧的单词 9灿烂的单词
	CreatedAt  string //
	UpdatedAt  string //
}

// enPracticeWordColumns holds the columns for table e_en_practice_word.
var enPracticeWordColumns = EnPracticeWordColumns{
	Id:         "id",
	Group:      "group",
	Uid:        "uid",
	En:         "en",
	Zh:         "zh",
	Sentence:   "sentence",
	SentenceZh: "sentence_zh",
	Count:      "count",
	Level:      "level",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

// NewEnPracticeWordDao creates and returns a new DAO object for table data access.
func NewEnPracticeWordDao() *EnPracticeWordDao {
	return &EnPracticeWordDao{
		group:   "default",
		table:   "e_en_practice_word",
		columns: enPracticeWordColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *EnPracticeWordDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *EnPracticeWordDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *EnPracticeWordDao) Columns() EnPracticeWordColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *EnPracticeWordDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *EnPracticeWordDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *EnPracticeWordDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
