// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// FreeKeyVisitLogDao is the data access object for table f_free_key_visit_log.
type FreeKeyVisitLogDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns FreeKeyVisitLogColumns // columns contains all the column names of Table for convenient usage.
}

// FreeKeyVisitLogColumns defines and stores column names for table f_free_key_visit_log.
type FreeKeyVisitLogColumns struct {
	Id        string //
	Visit     string //
	Max       string //
	CreatedAt string //
	UpdatedAt string //
}

// freeKeyVisitLogColumns holds the columns for table f_free_key_visit_log.
var freeKeyVisitLogColumns = FreeKeyVisitLogColumns{
	Id:        "id",
	Visit:     "visit",
	Max:       "max",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewFreeKeyVisitLogDao creates and returns a new DAO object for table data access.
func NewFreeKeyVisitLogDao() *FreeKeyVisitLogDao {
	return &FreeKeyVisitLogDao{
		group:   "default",
		table:   "f_free_key_visit_log",
		columns: freeKeyVisitLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *FreeKeyVisitLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *FreeKeyVisitLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *FreeKeyVisitLogDao) Columns() FreeKeyVisitLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *FreeKeyVisitLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *FreeKeyVisitLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *FreeKeyVisitLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
