// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// GoldDao is the data access object for table u_gold.
type GoldDao struct {
	table   string      // table is the underlying table name of the DAO.
	group   string      // group is the database configuration group name of current DAO.
	columns GoldColumns // columns contains all the column names of Table for convenient usage.
}

// GoldColumns defines and stores column names for table u_gold.
type GoldColumns struct {
	Id           string //
	Uid          string //
	Balance      string //
	Pass         string //
	PassErrCount string // 密码输错次数
	Desc         string //
	Status       string // 金库状态 0 设置密码 1正常,2 锁定
	CreatedAt    string //
	UpdatedAt    string //
}

//  goldColumns holds the columns for table u_gold.
var goldColumns = GoldColumns{
	Id:           "id",
	Uid:          "uid",
	Balance:      "balance",
	Pass:         "pass",
	PassErrCount: "pass_err_count",
	Desc:         "desc",
	Status:       "status",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

// NewGoldDao creates and returns a new DAO object for table data access.
func NewGoldDao() *GoldDao {
	return &GoldDao{
		group:   "default",
		table:   "u_gold",
		columns: goldColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *GoldDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *GoldDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *GoldDao) Columns() GoldColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *GoldDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *GoldDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *GoldDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
