// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// GoldChangeLogDao is the data access object for table u_gold_change_log.
type GoldChangeLogDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns GoldChangeLogColumns // columns contains all the column names of Table for convenient usage.
}

// GoldChangeLogColumns defines and stores column names for table u_gold_change_log.
type GoldChangeLogColumns struct {
	Id        string //
	TransId   string //
	Uid       string //
	Amount    string //
	Balance   string //
	Type      string // 1人工充值,2支付宝充值,3微信充值,4paypal充值,5人工扣除
	Desc      string //
	CreatedAt string //
}

//  goldChangeLogColumns holds the columns for table u_gold_change_log.
var goldChangeLogColumns = GoldChangeLogColumns{
	Id:        "id",
	TransId:   "trans_id",
	Uid:       "uid",
	Amount:    "amount",
	Balance:   "balance",
	Type:      "type",
	Desc:      "desc",
	CreatedAt: "created_at",
}

// NewGoldChangeLogDao creates and returns a new DAO object for table data access.
func NewGoldChangeLogDao() *GoldChangeLogDao {
	return &GoldChangeLogDao{
		group:   "default",
		table:   "u_gold_change_log",
		columns: goldChangeLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *GoldChangeLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *GoldChangeLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *GoldChangeLogDao) Columns() GoldChangeLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *GoldChangeLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *GoldChangeLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *GoldChangeLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
