// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// QuestionDao is the data access object for table q_question.
type QuestionDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns QuestionColumns // columns contains all the column names of Table for convenient usage.
}

// QuestionColumns defines and stores column names for table q_question.
type QuestionColumns struct {
	Id        string //
	Question  string //
	Category  string //
	Desc      string //
	Icon      string //
	EnContent string //
	Visit     string //
	Status    string //
	CreatedAt string //
}

// questionColumns holds the columns for table q_question.
var questionColumns = QuestionColumns{
	Id:        "id",
	Question:  "question",
	Category:  "category",
	Desc:      "desc",
	Icon:      "icon",
	EnContent: "en_content",
	Visit:     "visit",
	Status:    "status",
	CreatedAt: "created_at",
}

// NewQuestionDao creates and returns a new DAO object for table data access.
func NewQuestionDao() *QuestionDao {
	return &QuestionDao{
		group:   "default",
		table:   "q_question",
		columns: questionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *QuestionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *QuestionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *QuestionDao) Columns() QuestionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *QuestionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *QuestionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *QuestionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
