// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// QuotationsDao is the data access object for table q_quotations.
type QuotationsDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns QuotationsColumns // columns contains all the column names of Table for convenient usage.
}

// QuotationsColumns defines and stores column names for table q_quotations.
type QuotationsColumns struct {
	Id        string //
	Book      string // 书籍名称
	Writer    string // 作者名称
	Category  string // 类型
	Content   string //
	ContentEn string //
	Like      string // 喜欢的次数
	Status    string //
	CreatedAt string //
	UpdatedAt string //
}

// quotationsColumns holds the columns for table q_quotations.
var quotationsColumns = QuotationsColumns{
	Id:        "id",
	Book:      "book",
	Writer:    "writer",
	Category:  "category",
	Content:   "content",
	ContentEn: "content_en",
	Like:      "like",
	Status:    "status",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewQuotationsDao creates and returns a new DAO object for table data access.
func NewQuotationsDao() *QuotationsDao {
	return &QuotationsDao{
		group:   "default",
		table:   "q_quotations",
		columns: quotationsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *QuotationsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *QuotationsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *QuotationsDao) Columns() QuotationsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *QuotationsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *QuotationsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *QuotationsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
