// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ReadDao is the data access object for table r_read.
type ReadDao struct {
	table   string      // table is the underlying table name of the DAO.
	group   string      // group is the database configuration group name of current DAO.
	columns ReadColumns // columns contains all the column names of Table for convenient usage.
}

// ReadColumns defines and stores column names for table r_read.
type ReadColumns struct {
	Id          string //
	Category1   string //
	Category2   string //
	Tag         string //
	Title       string //
	Icon        string //
	Poster      string //
	Visit       string //
	Keywords    string //
	Writer      string //
	Description string //
	Content     string //
	Status      string //
	Sort        string //
	Recommend   string //
	CreatedAt   string //
	UpdatedAt   string //
}

// readColumns holds the columns for table r_read.
var readColumns = ReadColumns{
	Id:          "id",
	Category1:   "category_1",
	Category2:   "category_2",
	Tag:         "tag",
	Title:       "title",
	Icon:        "icon",
	Poster:      "poster",
	Visit:       "visit",
	Keywords:    "keywords",
	Writer:      "writer",
	Description: "description",
	Content:     "content",
	Status:      "status",
	Sort:        "sort",
	Recommend:   "recommend",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// NewReadDao creates and returns a new DAO object for table data access.
func NewReadDao() *ReadDao {
	return &ReadDao{
		group:   "default",
		table:   "r_read",
		columns: readColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ReadDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ReadDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ReadDao) Columns() ReadColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ReadDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ReadDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ReadDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
