// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// RelationLinkDao is the data access object for table k_relation_link.
type RelationLinkDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns RelationLinkColumns // columns contains all the column names of Table for convenient usage.
}

// RelationLinkColumns defines and stores column names for table k_relation_link.
type RelationLinkColumns struct {
	Id        string //
	Category  string //
	Name      string //
	Link      string //
	Summery   string //
	Desc      string //
	Sort      string //
	CreatedAt string //
}

// relationLinkColumns holds the columns for table k_relation_link.
var relationLinkColumns = RelationLinkColumns{
	Id:        "id",
	Category:  "category",
	Name:      "name",
	Link:      "link",
	Summery:   "summery",
	Desc:      "desc",
	Sort:      "sort",
	CreatedAt: "created_at",
}

// NewRelationLinkDao creates and returns a new DAO object for table data access.
func NewRelationLinkDao() *RelationLinkDao {
	return &RelationLinkDao{
		group:   "default",
		table:   "k_relation_link",
		columns: relationLinkColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RelationLinkDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *RelationLinkDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *RelationLinkDao) Columns() RelationLinkColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *RelationLinkDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RelationLinkDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RelationLinkDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
