// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TopUpCategoryDao is the data access object for table u_top_up_category.
type TopUpCategoryDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns TopUpCategoryColumns // columns contains all the column names of Table for convenient usage.
}

// TopUpCategoryColumns defines and stores column names for table u_top_up_category.
type TopUpCategoryColumns struct {
	Id       string //
	Title    string //
	SubTitle string //
	Type     string //
	Summary  string //
	Desc     string //
	Status   string //
}

//  topUpCategoryColumns holds the columns for table u_top_up_category.
var topUpCategoryColumns = TopUpCategoryColumns{
	Id:       "id",
	Title:    "title",
	SubTitle: "sub_title",
	Type:     "type",
	Summary:  "summary",
	Desc:     "desc",
	Status:   "status",
}

// NewTopUpCategoryDao creates and returns a new DAO object for table data access.
func NewTopUpCategoryDao() *TopUpCategoryDao {
	return &TopUpCategoryDao{
		group:   "default",
		table:   "u_top_up_category",
		columns: topUpCategoryColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TopUpCategoryDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TopUpCategoryDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TopUpCategoryDao) Columns() TopUpCategoryColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TopUpCategoryDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TopUpCategoryDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TopUpCategoryDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
