// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserStudyStatusDao is the data access object for table u_user_study_status.
type UserStudyStatusDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns UserStudyStatusColumns // columns contains all the column names of Table for convenient usage.
}

// UserStudyStatusColumns defines and stores column names for table u_user_study_status.
type UserStudyStatusColumns struct {
	Id                    string //
	Uid                   string //
	WordNum               string // 单词学习个数
	PersistInLearningDays string // 坚持学习天数
	LastLearningDate      string // 上次学习日期
	RedHardNum            string // 小红心个数
}

// userStudyStatusColumns holds the columns for table u_user_study_status.
var userStudyStatusColumns = UserStudyStatusColumns{
	Id:                    "id",
	Uid:                   "uid",
	WordNum:               "word_num",
	PersistInLearningDays: "persist_in_learning_days",
	LastLearningDate:      "last_learning_date",
	RedHardNum:            "red_hard_num",
}

// NewUserStudyStatusDao creates and returns a new DAO object for table data access.
func NewUserStudyStatusDao() *UserStudyStatusDao {
	return &UserStudyStatusDao{
		group:   "default",
		table:   "u_user_study_status",
		columns: userStudyStatusColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserStudyStatusDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserStudyStatusDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserStudyStatusDao) Columns() UserStudyStatusColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserStudyStatusDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserStudyStatusDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserStudyStatusDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
