// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WalletStatisticsLogDao is the data access object for table u_wallet_statistics_log.
type WalletStatisticsLogDao struct {
	table   string                     // table is the underlying table name of the DAO.
	group   string                     // group is the database configuration group name of current DAO.
	columns WalletStatisticsLogColumns // columns contains all the column names of Table for convenient usage.
}

// WalletStatisticsLogColumns defines and stores column names for table u_wallet_statistics_log.
type WalletStatisticsLogColumns struct {
	Id          string //
	Uid         string //
	T1          string //
	T2          string //
	T3          string //
	T4          string //
	T5          string //
	T6          string //
	T7          string //
	T8          string //
	T9          string //
	T10         string //
	T11         string //
	T12         string //
	T13         string //
	CreatedDate string //
}

// walletStatisticsLogColumns holds the columns for table u_wallet_statistics_log.
var walletStatisticsLogColumns = WalletStatisticsLogColumns{
	Id:          "id",
	Uid:         "uid",
	T1:          "t1",
	T2:          "t2",
	T3:          "t3",
	T4:          "t4",
	T5:          "t5",
	T6:          "t6",
	T7:          "t7",
	T8:          "t8",
	T9:          "t9",
	T10:         "t10",
	T11:         "t11",
	T12:         "t12",
	T13:         "t13",
	CreatedDate: "created_date",
}

// NewWalletStatisticsLogDao creates and returns a new DAO object for table data access.
func NewWalletStatisticsLogDao() *WalletStatisticsLogDao {
	return &WalletStatisticsLogDao{
		group:   "default",
		table:   "u_wallet_statistics_log",
		columns: walletStatisticsLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WalletStatisticsLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WalletStatisticsLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *WalletStatisticsLogDao) Columns() WalletStatisticsLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *WalletStatisticsLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WalletStatisticsLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WalletStatisticsLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
