// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-begin/internal/consts"
	"ciel-begin/internal/model/entity"
	"ciel-begin/internal/service/internal/dao/internal"
	"context"
)

// adminDao is the data access object for table s_admin.
// You can define custom methods on it to extend its functionality as you wish.
type adminDao struct {
	*internal.AdminDao
}

func (d adminDao) GetByUname(ctx context.Context, uname string) (*entity.Admin, error) {
	var data entity.Admin
	one, err := d.Ctx(ctx).One("uname", uname)
	if err != nil {
		return nil, err
	}
	if one.IsEmpty() {
		return nil, consts.ErrLogin
	}
	err = one.Struct(&data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}

func (d adminDao) Update(ctx context.Context, admin *entity.Admin) error {
	_, err := d.Ctx(ctx).Update(admin, "id", admin.Id)
	if err != nil {
		return err
	}
	return nil
}

var (
	// Admin is globally public accessible object for table s_admin operations.
	Admin = adminDao{
		internal.NewAdminDao(),
	}
)

// Fill with you ideas below.
