// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/service/internal/dao/internal"
)

// diaryDao is the data access object for table c_diary.
// You can define custom methods on it to extend its functionality as you wish.
type diaryDao struct {
	*internal.DiaryDao
}

var (
	// Diary is globally public accessible object for table c_diary operations.
	Diary = diaryDao{
		internal.NewDiaryDao(),
	}
)

// Fill with you ideas below.
