// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/service/internal/dao/internal"
)

// nodeDao is the data access object for table f_node.
// You can define custom methods on it to extend its functionality as you wish.
type nodeDao struct {
	*internal.NodeDao
}

var (
	// Node is globally public accessible object for table f_node operations.
	Node = nodeDao{
		internal.NewNodeDao(),
	}
)

// Fill with you ideas below.
