// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/service/internal/dao/internal"
)

// thingRecordDao is the data access object for table f_thing_record.
// You can define custom methods on it to extend its functionality as you wish.
type thingRecordDao struct {
	*internal.ThingRecordDao
}

var (
	// ThingRecord is globally public accessible object for table f_thing_record operations.
	ThingRecord = thingRecordDao{
		internal.NewThingRecordDao(),
	}
)

// Fill with you ideas below.
