### 通知管理员
GET {{url}}/admin/sys/noticeAdmin?msg=你有新的信息

### 字典表
GET {{url}}/v1/sys/allDict

### 查询单个字典信息
GET {{url}}/v1/sys/dict?key=great

### 查询banners
GET {{url}}/v1/sys/banners

### 上传图片
POST {{url}}/v1/sys/uploadImg?group=2
Authorization: {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Lark20201204183701.png"
Content-Type: image/png

< /Users/ciel/learn/v3_freekey/resource/public/cat.jpg

--WebAppBoundary
Content-Disposition: form-data; name="group"
Content-Type: text/plain
