### 用户注册
POST {{url}}/v1/user/register
Content-Type: application/json

{
  "uname": "user33",
  "pass": "FM0WPhQb"
}

> {%
    client.global.set("token", response.body.data.token);
%}

### 用户登录
POST {{url}}/v1/user/login
Content-Type: application/json

{
  "uname": "user33",
  "pass": "FM0WPhQb"
}

> {%
    client.global.set("token", response.body.data.token);
%}

### 登录信息
GET {{url}}/v1/user/info
Authorization: {{token}}

### 修改密码
POST {{url}}/v1/user/updatePass
Content-Type: application/json
Authorization: {{token}}

{
  "oldPass": "FM0WPhQb",
  "newPass": "a1231231"
}

### 修改昵称
POST {{url}}/v1/user/updateNickname
Content-Type: application/json
Authorization: {{token}}

{
  "nickname": "user33"
}

### 查看可选择的头像
GET {{url}}/v1/user/icons
Content-Type: application/json

### 修改头像
POST {{url}}/v1/user/updateIcon
Content-Type: application/json
Authorization: {{token}}

{
  "icon": "icon/icon43.png"
}

### 设置钱包密码
POST {{url}}/v1/wallet/setPass
Content-Type: application/json
Authorization: {{token}}

{
  "pass": "123456"
}

### 修改钱包密码
POST {{url}}/v1/wallet/updatePass
Authorization: {{token}}
Content-Type: application/json

{
  "oldPass": "111111",
  "newPass": "123456"
}

### 查询充值类型
GET {{url}}/v1/wallet/topUpCategory
Authorization: {{token}}

### 创建充值订单
POST {{url}}/v1/wallet/createTopUp
Authorization: {{token}}
Content-Type: application/json

{
  "change_type_id": 1,
  "money": 10
}

### 查询充值订单列表
GET {{url}}/v1/wallet/listTopUp?page=1&size=10&status=
Authorization: {{token}}

### 查询账变类型
GET {{url}}/v1/wallet/listChangeTypes
Authorization: {{token}}

### 查询账变列表
GET {{url}}/v1/wallet/listChangeLogs?page=1&size=1&type=
Authorization: {{token}}

### 查询钱包信息
GET {{url}}/v1/wallet/getInfo
Authorization: {{token}}