// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/consts"
	"ciel-admin/internal/dao/internal"
	"ciel-admin/internal/model/entity"
	"context"
	"github.com/gogf/gf/v2/frame/g"
)

// internalApiDao is internal type for wrapping internal DAO implements.
type internalApiDao = *internal.ApiDao

// apiDao is the data access object for table s_api.
// You can define custom methods on it to extend its functionality as you wish.
type apiDao struct {
	internalApiDao
}

func (d apiDao) GetById(ctx context.Context, id interface{}) (*entity.Api, error) {
	var data entity.Api
	one, err := d.Ctx(ctx).WherePri(id).One()
	if err != nil {
		return nil, err
	}
	if one.IsEmpty() {
		return nil, consts.ErrDataNotFound
	}
	if err = one.Struct(&data); err != nil {
		g.Log().Error(ctx, err)
		return nil, err
	}
	return &data, nil
}

var (
	// Api is globally public accessible object for table s_api operations.
	Api = apiDao{
		internal.NewApiDao(),
	}
)

// Fill with you ideas below.
