// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalBookWriterDao is internal type for wrapping internal DAO implements.
type internalBookWriterDao = *internal.BookWriterDao

// bookWriterDao is the data access object for table b_book_writer.
// You can define custom methods on it to extend its functionality as you wish.
type bookWriterDao struct {
	internalBookWriterDao
}

var (
	// BookWriter is globally public accessible object for table b_book_writer operations.
	BookWriter = bookWriterDao{
		internal.NewBookWriterDao(),
	}
)

// Fill with you ideas below.
