// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEnDocumentParagraphDao is internal type for wrapping internal DAO implements.
type internalEnDocumentParagraphDao = *internal.EnDocumentParagraphDao

// enDocumentParagraphDao is the data access object for table e_en_document_paragraph.
// You can define custom methods on it to extend its functionality as you wish.
type enDocumentParagraphDao struct {
	internalEnDocumentParagraphDao
}

var (
	// EnDocumentParagraph is globally public accessible object for table e_en_document_paragraph operations.
	EnDocumentParagraph = enDocumentParagraphDao{
		internal.NewEnDocumentParagraphDao(),
	}
)

// Fill with you ideas below.
