// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEnDocumentUserDao is internal type for wrapping internal DAO implements.
type internalEnDocumentUserDao = *internal.EnDocumentUserDao

// enDocumentUserDao is the data access object for table e_en_document_user.
// You can define custom methods on it to extend its functionality as you wish.
type enDocumentUserDao struct {
	internalEnDocumentUserDao
}

var (
	// EnDocumentUser is globally public accessible object for table e_en_document_user operations.
	EnDocumentUser = enDocumentUserDao{
		internal.NewEnDocumentUserDao(),
	}
)

// Fill with you ideas below.
