// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEnDocumentDao is internal type for wrapping internal DAO implements.
type internalEnDocumentDao = *internal.EnDocumentDao

// enDocumentDao is the data access object for table e_en_document.
// You can define custom methods on it to extend its functionality as you wish.
type enDocumentDao struct {
	internalEnDocumentDao
}

var (
	// EnDocument is globally public accessible object for table e_en_document operations.
	EnDocument = enDocumentDao{
		internal.NewEnDocumentDao(),
	}
)

// Fill with you ideas below.
