// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEnDocumentParagraphWordDao is internal type for wrapping internal DAO implements.
type internalEnDocumentParagraphWordDao = *internal.EnDocumentParagraphWordDao

// enDocumentParagraphWordDao is the data access object for table e_en_document_paragraph_word.
// You can define custom methods on it to extend its functionality as you wish.
type enDocumentParagraphWordDao struct {
	internalEnDocumentParagraphWordDao
}

var (
	// EnDocumentParagraphWord is globally public accessible object for table e_en_document_paragraph_word operations.
	EnDocumentParagraphWord = enDocumentParagraphWordDao{
		internal.NewEnDocumentParagraphWordDao(),
	}
)

// Fill with you ideas below.
