// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEnDocumentParagraphUserDao is internal type for wrapping internal DAO implements.
type internalEnDocumentParagraphUserDao = *internal.EnDocumentParagraphUserDao

// enDocumentParagraphUserDao is the data access object for table e_en_document_paragraph_user.
// You can define custom methods on it to extend its functionality as you wish.
type enDocumentParagraphUserDao struct {
	internalEnDocumentParagraphUserDao
}

var (
	// EnDocumentParagraphUser is globally public accessible object for table e_en_document_paragraph_user operations.
	EnDocumentParagraphUser = enDocumentParagraphUserDao{
		internal.NewEnDocumentParagraphUserDao(),
	}
)

// Fill with you ideas below.
