// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEnPracticeWordCountDao is internal type for wrapping internal DAO implements.
type internalEnPracticeWordCountDao = *internal.EnPracticeWordCountDao

// enPracticeWordCountDao is the data access object for table e_en_practice_word_count.
// You can define custom methods on it to extend its functionality as you wish.
type enPracticeWordCountDao struct {
	internalEnPracticeWordCountDao
}

var (
	// EnPracticeWordCount is globally public accessible object for table e_en_practice_word_count operations.
	EnPracticeWordCount = enPracticeWordCountDao{
		internal.NewEnPracticeWordCountDao(),
	}
)

// Fill with you ideas below.
