// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEnPracticeWordDao is internal type for wrapping internal DAO implements.
type internalEnPracticeWordDao = *internal.EnPracticeWordDao

// enPracticeWordDao is the data access object for table e_en_practice_word.
// You can define custom methods on it to extend its functionality as you wish.
type enPracticeWordDao struct {
	internalEnPracticeWordDao
}

var (
	// EnPracticeWord is globally public accessible object for table e_en_practice_word operations.
	EnPracticeWord = enPracticeWordDao{
		internal.NewEnPracticeWordDao(),
	}
)

// Fill with you ideas below.
