// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEnUserWordDao is internal type for wrapping internal DAO implements.
type internalEnUserWordDao = *internal.EnUserWordDao

// enUserWordDao is the data access object for table e_en_user_word.
// You can define custom methods on it to extend its functionality as you wish.
type enUserWordDao struct {
	internalEnUserWordDao
}

var (
	// EnUserWord is globally public accessible object for table e_en_user_word operations.
	EnUserWord = enUserWordDao{
		internal.NewEnUserWordDao(),
	}
)

// Fill with you ideas below.
