// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEnWordStudyLogDao is internal type for wrapping internal DAO implements.
type internalEnWordStudyLogDao = *internal.EnWordStudyLogDao

// enWordStudyLogDao is the data access object for table e_en_word_study_log.
// You can define custom methods on it to extend its functionality as you wish.
type enWordStudyLogDao struct {
	internalEnWordStudyLogDao
}

var (
	// EnWordStudyLog is globally public accessible object for table e_en_word_study_log operations.
	EnWordStudyLog = enWordStudyLogDao{
		internal.NewEnWordStudyLogDao(),
	}
)

// Fill with you ideas below.
