// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalEventDao is internal type for wrapping internal DAO implements.
type internalEventDao = *internal.EventDao

// eventDao is the data access object for table e_event.
// You can define custom methods on it to extend its functionality as you wish.
type eventDao struct {
	internalEventDao
}

var (
	// Event is globally public accessible object for table e_event operations.
	Event = eventDao{
		internal.NewEventDao(),
	}
)

// Fill with you ideas below.
