// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/consts"
	"ciel-admin/internal/dao/internal"
	"ciel-admin/internal/model/entity"
	"context"
)

// internalFileDao is internal type for wrapping internal DAO implements.
type internalFileDao = *internal.FileDao

// fileDao is the data access object for table s_file.
// You can define custom methods on it to extend its functionality as you wish.
type fileDao struct {
	internalFileDao
}

var (
	// File is globally public accessible object for table s_file operations.
	File = fileDao{
		internal.NewFileDao(),
	}
)

// Fill with you ideas below.

func (d fileDao) GetById(ctx context.Context, id interface{}) (*entity.File, error) {
	var data entity.File
	one, err := d.Ctx(ctx).Where("id", id).One()
	if err != nil {
		return nil, err
	}
	if one.IsEmpty() {
		return nil, consts.ErrDataNotFound
	}
	if err = one.Struct(&data); err != nil {
		return nil, err
	}
	return &data, nil
}
