// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalFreeKeyVisitLogDao is internal type for wrapping internal DAO implements.
type internalFreeKeyVisitLogDao = *internal.FreeKeyVisitLogDao

// freeKeyVisitLogDao is the data access object for table f_free_key_visit_log.
// You can define custom methods on it to extend its functionality as you wish.
type freeKeyVisitLogDao struct {
	internalFreeKeyVisitLogDao
}

var (
	// FreeKeyVisitLog is globally public accessible object for table f_free_key_visit_log operations.
	FreeKeyVisitLog = freeKeyVisitLogDao{
		internal.NewFreeKeyVisitLogDao(),
	}
)

// Fill with you ideas below.
