// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalGoldChangeLogDao is internal type for wrapping internal DAO implements.
type internalGoldChangeLogDao = *internal.GoldChangeLogDao

// goldChangeLogDao is the data access object for table u_gold_change_log.
// You can define custom methods on it to extend its functionality as you wish.
type goldChangeLogDao struct {
	internalGoldChangeLogDao
}

var (
	// GoldChangeLog is globally public accessible object for table u_gold_change_log operations.
	GoldChangeLog = goldChangeLogDao{
		internal.NewGoldChangeLogDao(),
	}
)

// Fill with you ideas below.
