// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/consts"
	"ciel-admin/internal/dao/internal"
	"ciel-admin/internal/model/entity"
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// internalGoldDao is internal type for wrapping internal DAO implements.
type internalGoldDao = *internal.GoldDao

// goldDao is the data access object for table u_gold.
// You can define custom methods on it to extend its functionality as you wish.
type goldDao struct {
	internalGoldDao
}

func (d goldDao) GetByUidTx(ctx context.Context, tx *gdb.TX, id uint64) (*entity.Gold, error) {
	var data entity.Gold
	one, err := tx.Ctx(ctx).Model(d.Table()).One("uid", id)
	if err != nil {
		g.Log().Error(ctx, err)
		return nil, err
	}
	if one.IsEmpty() {
		g.Log().Errorf(ctx, "%d 钱包信息不存在", id)
		return nil, consts.ErrDataNotFound
	}
	if err = one.Struct(&data); err != nil {
		g.Log().Error(ctx, err)
		return nil, err
	}
	return &data, nil
}

var (
	// Gold is globally public accessible object for table u_gold operations.
	Gold = goldDao{
		internal.NewGoldDao(),
	}
)

// Fill with you ideas below.
