// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/consts"
	"ciel-admin/internal/dao/internal"
	"ciel-admin/internal/model/entity"
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// internalGoldStatisticsLogDao is internal type for wrapping internal DAO implements.
type internalGoldStatisticsLogDao = *internal.GoldStatisticsLogDao

// goldStatisticsLogDao is the data access object for table u_gold_statistics_log.
// You can define custom methods on it to extend its functionality as you wish.
type goldStatisticsLogDao struct {
	internalGoldStatisticsLogDao
}

func (d goldStatisticsLogDao) GetTodayLog(ctx context.Context, tx *gdb.TX, uid uint64) (*entity.GoldStatisticsLog, error) {
	var data entity.GoldStatisticsLog
	one, err := tx.Model(d.Table()).Where("uid = ? and created_date>=?", uid, gtime.Date()).One()
	if err != nil {
		g.Log().Error(ctx, err)
		return nil, err
	}
	if one.IsEmpty() {
		return nil, consts.ErrDataNotFound
	}
	if err = one.Struct(&data); err != nil {
		return nil, err
	}
	return &data, nil
}

var (
	// GoldStatisticsLog is globally public accessible object for table u_gold_statistics_log operations.
	GoldStatisticsLog = goldStatisticsLogDao{
		internal.NewGoldStatisticsLogDao(),
	}
)

// Fill with you ideas below.
