// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalKnowledgeDao is internal type for wrapping internal DAO implements.
type internalKnowledgeDao = *internal.KnowledgeDao

// knowledgeDao is the data access object for table k_knowledge.
// You can define custom methods on it to extend its functionality as you wish.
type knowledgeDao struct {
	internalKnowledgeDao
}

var (
	// Knowledge is globally public accessible object for table k_knowledge operations.
	Knowledge = knowledgeDao{
		internal.NewKnowledgeDao(),
	}
)

// Fill with you ideas below.
