// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalQuestionDao is internal type for wrapping internal DAO implements.
type internalQuestionDao = *internal.QuestionDao

// questionDao is the data access object for table q_question.
// You can define custom methods on it to extend its functionality as you wish.
type questionDao struct {
	internalQuestionDao
}

var (
	// Question is globally public accessible object for table q_question operations.
	Question = questionDao{
		internal.NewQuestionDao(),
	}
)

// Fill with you ideas below.
