// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalQuestionCategoryDao is internal type for wrapping internal DAO implements.
type internalQuestionCategoryDao = *internal.QuestionCategoryDao

// questionCategoryDao is the data access object for table q_question_category.
// You can define custom methods on it to extend its functionality as you wish.
type questionCategoryDao struct {
	internalQuestionCategoryDao
}

var (
	// QuestionCategory is globally public accessible object for table q_question_category operations.
	QuestionCategory = questionCategoryDao{
		internal.NewQuestionCategoryDao(),
	}
)

// Fill with you ideas below.
