// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalQuotationsDao is internal type for wrapping internal DAO implements.
type internalQuotationsDao = *internal.QuotationsDao

// quotationsDao is the data access object for table q_quotations.
// You can define custom methods on it to extend its functionality as you wish.
type quotationsDao struct {
	internalQuotationsDao
}

var (
	// Quotations is globally public accessible object for table q_quotations operations.
	Quotations = quotationsDao{
		internal.NewQuotationsDao(),
	}
)

// Fill with you ideas below.
