// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalReadCategoryDao is internal type for wrapping internal DAO implements.
type internalReadCategoryDao = *internal.ReadCategoryDao

// readCategoryDao is the data access object for table r_read_category.
// You can define custom methods on it to extend its functionality as you wish.
type readCategoryDao struct {
	internalReadCategoryDao
}

var (
	// ReadCategory is globally public accessible object for table r_read_category operations.
	ReadCategory = readCategoryDao{
		internal.NewReadCategoryDao(),
	}
)

// Fill with you ideas below.
