// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalReadDao is internal type for wrapping internal DAO implements.
type internalReadDao = *internal.ReadDao

// readDao is the data access object for table r_read.
// You can define custom methods on it to extend its functionality as you wish.
type readDao struct {
	internalReadDao
}

var (
	// Read is globally public accessible object for table r_read operations.
	Read = readDao{
		internal.NewReadDao(),
	}
)

// Fill with you ideas below.
