// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalThingDao is internal type for wrapping internal DAO implements.
type internalThingDao = *internal.ThingDao

// thingDao is the data access object for table f_thing.
// You can define custom methods on it to extend its functionality as you wish.
type thingDao struct {
	internalThingDao
}

var (
	// Thing is globally public accessible object for table f_thing operations.
	Thing = thingDao{
		internal.NewThingDao(),
	}
)

// Fill with you ideas below.
