// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalTopUpCategoryDao is internal type for wrapping internal DAO implements.
type internalTopUpCategoryDao = *internal.TopUpCategoryDao

// topUpCategoryDao is the data access object for table u_top_up_category.
// You can define custom methods on it to extend its functionality as you wish.
type topUpCategoryDao struct {
	internalTopUpCategoryDao
}

var (
	// TopUpCategory is globally public accessible object for table u_top_up_category operations.
	TopUpCategory = topUpCategoryDao{
		internal.NewTopUpCategoryDao(),
	}
)

// Fill with you ideas below.
