// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalUserStudyStatusDao is internal type for wrapping internal DAO implements.
type internalUserStudyStatusDao = *internal.UserStudyStatusDao

// userStudyStatusDao is the data access object for table u_user_study_status.
// You can define custom methods on it to extend its functionality as you wish.
type userStudyStatusDao struct {
	internalUserStudyStatusDao
}

var (
	// UserStudyStatus is globally public accessible object for table u_user_study_status operations.
	UserStudyStatus = userStudyStatusDao{
		internal.NewUserStudyStatusDao(),
	}
)

// Fill with you ideas below.
