// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalWalletTopUpApplicationDao is internal type for wrapping internal DAO implements.
type internalWalletTopUpApplicationDao = *internal.WalletTopUpApplicationDao

// walletTopUpApplicationDao is the data access object for table u_wallet_top_up_application.
// You can define custom methods on it to extend its functionality as you wish.
type walletTopUpApplicationDao struct {
	internalWalletTopUpApplicationDao
}

var (
	// WalletTopUpApplication is globally public accessible object for table u_wallet_top_up_application operations.
	WalletTopUpApplication = walletTopUpApplicationDao{
		internal.NewWalletTopUpApplicationDao(),
	}
)

// Fill with you ideas below.
