// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ciel-admin/internal/dao/internal"
)

// internalWalletChangeTypeDao is internal type for wrapping internal DAO implements.
type internalWalletChangeTypeDao = *internal.WalletChangeTypeDao

// walletChangeTypeDao is the data access object for table u_wallet_change_type.
// You can define custom methods on it to extend its functionality as you wish.
type walletChangeTypeDao struct {
	internalWalletChangeTypeDao
}

var (
	// WalletChangeType is globally public accessible object for table u_wallet_change_type operations.
	WalletChangeType = walletChangeTypeDao{
		internal.NewWalletChangeTypeDao(),
	}
)

// Fill with you ideas below.
