// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-09 17:01:42
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Diary is the golang structure of table c_diary for DAO operations like Where/Data.
type Diary struct {
	g.Meta    `orm:"table:c_diary, do:true"`
	Id        interface{} //
	Aid       interface{} //
	Title     interface{} //
	Level     interface{} //
	Content   interface{} //
	Sign1     interface{} //
	Sign2     interface{} //
	Sign3     interface{} //
	Sign4     interface{} //
	Sign5     interface{} //
	Sign6     interface{} //
	Sign7     interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
