// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-09 17:01:42
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Dict is the golang structure of table s_dict for DAO operations like Where/Data.
type Dict struct {
	g.Meta    `orm:"table:s_dict, do:true"`
	Id        interface{} //
	K         interface{} //
	V         interface{} //
	Desc      interface{} //
	Group     interface{} //
	Status    interface{} //
	Type      interface{} // 1 文本，2 img
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
