// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ThingRecord is the golang structure of table f_thing_record for DAO operations like Where/Data.
type ThingRecord struct {
	g.Meta     `orm:"table:f_thing_record, do:true"`
	Id         interface{} //
	Tid        interface{} //
	RecordDate *gtime.Time //
	Score      interface{} //
	Day        interface{} //
	Desc       interface{} //
	CreatedAt  *gtime.Time //
}
