// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table u_user for DAO operations like Where/Data.
type User struct {
	g.Meta    `orm:"table:u_user, do:true"`
	Id        interface{} //
	Uname     interface{} //
	Nickname  interface{} //
	Pwd       interface{} //
	Email     interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
