// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMessage is the golang structure for table admin_message.
type AdminMessage struct {
	Id        uint64      `json:"id"        description:""`
	Aid       uint64      `json:"aid"       description:""`
	Type      uint        `json:"type"      description:"1 系统消息"`
	Title     string      `json:"title"     description:""`
	Content   string      `json:"content"   description:""`
	Url       string      `json:"url"       description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
}
