// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMessage is the golang structure for table admin_message.
type AdminMessage struct {
	Id        uint64      `json:"id"        description:""`
	FromUid   int         `json:"fromUid"   description:""`
	ToUid     int         `json:"toUid"     description:""`
	Group     int         `json:"group"     description:"{\"Label\":\"分组\",\"FieldType\":\"select\",\"SearchType\":1,\"Required\":1,\"Options\":\"1:系统:tag-info,2:管理员:tag-warning,3:其他:tag-danger\"}"`
	Type      int         `json:"type"      description:"{\"Label\":\"类型\",\"FieldType\":\"select\",\"SearchType\":1,\"Required\":1,\"Options\":\"1:文字:tag-info,2:图片:tag-primary,3:语音:tag-warning,4:视频:tag-success,5:链接:tag-danger\"}"`
	Content   string      `json:"content"   description:"{\"Label\":\"内容\",\"SearchType\":2,\"Required\":1}"`
	Link      string      `json:"link"      description:"{\"Label\":\"链接\",\"SearchType\":2}"`
	Status    int         `json:"status"    description:"{\"Label\":\"状态\",\"FieldType\":\"select\",\"Options\":\"1:未读:tag-warning,2已读:tag-info\"}"`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
