// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Api is the golang structure for table api.
type Api struct {
	Id        uint64      `json:"id"        description:""`
	Url       string      `json:"url"       description:""`
	Method    string      `json:"method"    description:""`
	Group     string      `json:"group"     description:""`
	Type      uint        `json:"type"      description:"类型 1添加 2删除 3修改 4查看 5 页面"`
	Desc      string      `json:"desc"      description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
