// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BookWriter is the golang structure for table book_writer.
type BookWriter struct {
	Id        uint64      `json:"id"        description:""`
	Name      string      `json:"name"      description:""`
	Desc      string      `json:"desc"      description:""`
	Year      int         `json:"year"      description:""`
	Status    int         `json:"status"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
