// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BookChapter is the golang structure for table book_chapter.
type BookChapter struct {
	Id            uint64      `json:"id"            description:""`
	BookId        uint64      `json:"bookId"        description:""`
	Title         string      `json:"title"         description:""`
	Sort          int         `json:"sort"          description:""`
	Desc          string      `json:"desc"          description:""`
	Visit         uint64      `json:"visit"         description:""`
	Content       string      `json:"content"       description:""`
	ContentLength uint        `json:"contentLength" description:"正文字符数"`
	Status        uint        `json:"status"        description:""`
	Keywords      string      `json:"keywords"      description:""`
	Last          string      `json:"last"          description:""`
	Next          string      `json:"next"          description:""`
	CreatedAt     *gtime.Time `json:"createdAt"     description:""`
	UpdatedAt     *gtime.Time `json:"updatedAt"     description:""`
}
