// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// BookCategory is the golang structure for table book_category.
type BookCategory struct {
	Id      uint64  `json:"id"      description:""`
	Name    string  `json:"name"    description:""`
	Icon    string  `json:"icon"    description:""`
	Poster  string  `json:"poster"  description:""`
	Speak   string  `json:"speak"   description:""`
	Mark    string  `json:"mark"    description:""`
	Desc    string  `json:"desc"    description:""`
	BookNum uint    `json:"bookNum" description:""`
	Sort    float64 `json:"sort"    description:""`
	Status  uint    `json:"status"  description:""`
}
