// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Book is the golang structure for table book.
type Book struct {
	Id              uint64      `json:"id"              description:""`
	Name            string      `json:"name"            description:""`
	Writer          string      `json:"writer"          description:""`
	Category        string      `json:"category"        description:""`
	Icon            string      `json:"icon"            description:""`
	Poster          string      `json:"poster"          description:""`
	Year            int         `json:"year"            description:""`
	YearStatus      int         `json:"yearStatus"      description:"1准确，2大概"`
	Keywords        string      `json:"keywords"        description:""`
	Description     string      `json:"description"     description:""`
	ShortDesc       string      `json:"shortDesc"       description:""`
	Summary         string      `json:"summary"         description:"简介"`
	Quotations      string      `json:"quotations"      description:"名言"`
	RelationBooks   string      `json:"relationBooks"   description:""`
	Visit           uint64      `json:"visit"           description:""`
	Sort            uint        `json:"sort"            description:""`
	RecommendStatus uint        `json:"recommendStatus" description:"是否推荐 1是 2否"`
	Status          uint        `json:"status"          description:""`
	KnowledgeStatus uint        `json:"knowledgeStatus" description:""`
	CreatedAt       *gtime.Time `json:"createdAt"       description:""`
	UpdatedAt       *gtime.Time `json:"updatedAt"       description:""`
}
