// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-09 17:01:42
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Diary is the golang structure for table diary.
type Diary struct {
	Id        int         `json:"id"        description:""`
	Aid       int         `json:"aid"       description:""`
	Title     string      `json:"title"     description:""`
	Level     int         `json:"level"     description:""`
	Content   string      `json:"content"   description:""`
	Sign1     string      `json:"sign1"     description:""`
	Sign2     string      `json:"sign2"     description:""`
	Sign3     string      `json:"sign3"     description:""`
	Sign4     string      `json:"sign4"     description:""`
	Sign5     string      `json:"sign5"     description:""`
	Sign6     string      `json:"sign6"     description:""`
	Sign7     string      `json:"sign7"     description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
