// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// EnDocumentUser is the golang structure for table en_document_user.
type EnDocumentUser struct {
	Id         uint64 `json:"id"         description:""`
	DocumentId uint64 `json:"documentId" description:""`
	Uid        uint64 `json:"uid"        description:""`
	Level      uint   `json:"level"      description:""`
}
