// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EnDocument is the golang structure for table en_document.
type EnDocument struct {
	Id           uint64      `json:"id"           description:""`
	Category1    string      `json:"category1"    description:""`
	Category2    string      `json:"category2"    description:""`
	Title        string      `json:"title"        description:""`
	En           string      `json:"en"           description:""`
	Desc         string      `json:"desc"         description:""`
	Icon         string      `json:"icon"         description:""`
	Poster       string      `json:"poster"       description:""`
	WordNum      uint        `json:"wordNum"      description:"单词个数"`
	ParagraphNum uint        `json:"paragraphNum" description:"段落个数"`
	Sort         uint        `json:"sort"         description:""`
	Status       uint        `json:"status"       description:""`
	CreatedAt    *gtime.Time `json:"createdAt"    description:""`
	UpdatedAt    *gtime.Time `json:"updatedAt"    description:""`
}
