// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// EnDocumentParagraph is the golang structure for table en_document_paragraph.
type EnDocumentParagraph struct {
	Id         uint64 `json:"id"         description:""`
	DocumentId uint64 `json:"documentId" description:""`
	H2         string `json:"h2"         description:""`
	H3         string `json:"h3"         description:""`
	WordNum    uint   `json:"wordNum"    description:""`
	Content    string `json:"content"    description:""`
}
