// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// EnDocumentParagraphUser is the golang structure for table en_document_paragraph_user.
type EnDocumentParagraphUser struct {
	Id          uint64 `json:"id"          description:""`
	ParagraphId uint64 `json:"paragraphId" description:""`
	Uid         uint64 `json:"uid"         description:""`
	Level       uint   `json:"level"       description:""`
	Progress    uint   `json:"progress"    description:""`
}
