// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// EnDocumentParagraphWord is the golang structure for table en_document_paragraph_word.
type EnDocumentParagraphWord struct {
	Id          uint64 `json:"id"          description:""`
	ParagraphId uint64 `json:"paragraphId" description:""`
	En          string `json:"en"          description:""`
	Zh          string `json:"zh"          description:""`
	Sentence    string `json:"sentence"    description:""`
	SentenceZh  string `json:"sentenceZh"  description:""`
}
