// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EnDocumentParagraphWordUser is the golang structure for table en_document_paragraph_word_user.
type EnDocumentParagraphWordUser struct {
	Id         uint64      `json:"id"         description:""`
	WordId     uint64      `json:"wordId"     description:""`
	Uid        uint64      `json:"uid"        description:""`
	Level      uint        `json:"level"      description:""`
	Count      uint        `json:"count"      description:""`
	StudyDate  *gtime.Time `json:"studyDate"  description:""`
	HasBeenAdd uint        `json:"hasBeenAdd" description:""`
}
