// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EnPracticeWord is the golang structure for table en_practice_word.
type EnPracticeWord struct {
	Id         uint64      `json:"id"         description:""`
	Group      string      `json:"group"      description:""`
	Uid        uint64      `json:"uid"        description:""`
	En         string      `json:"en"         description:""`
	Zh         string      `json:"zh"         description:""`
	Sentence   string      `json:"sentence"   description:""`
	SentenceZh string      `json:"sentenceZh" description:""`
	Count      uint        `json:"count"      description:""`
	Level      uint        `json:"level"      description:"1单词粉末 2单词碎片 3单词 4小单词 5大单词 6硕大的单词 7闪光的单词 8燃烧的单词 9灿烂的单词"`
	CreatedAt  *gtime.Time `json:"createdAt"  description:""`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:""`
}
