// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// EnPracticeWordCount is the golang structure for table en_practice_word_count.
type EnPracticeWordCount struct {
	Id      uint64 `json:"id"      description:""`
	Uid     uint64 `json:"uid"     description:""`
	Level1  uint   `json:"level1"  description:""`
	Level2  uint   `json:"level2"  description:""`
	Level3  uint   `json:"level3"  description:""`
	Level4  uint   `json:"level4"  description:""`
	Level5  uint   `json:"level5"  description:""`
	Level6  uint   `json:"level6"  description:""`
	Level7  uint   `json:"level7"  description:""`
	Level8  uint   `json:"level8"  description:""`
	Level9  uint   `json:"level9"  description:""`
	Level10 uint   `json:"level10" description:""`
}
