// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EnUserWord is the golang structure for table en_user_word.
type EnUserWord struct {
	Uid       uint64      `json:"uid"       description:""`
	Word      string      `json:"word"      description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
}
