// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// EnWordStudyLog is the golang structure for table en_word_study_log.
type EnWordStudyLog struct {
	Uid         uint64      `json:"uid"         description:""`
	CreatedDate *gtime.Time `json:"createdDate" description:""`
	Num         uint        `json:"num"         description:""`
}
