// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Event is the golang structure for table event.
type Event struct {
	Id        uint64      `json:"id"        description:""`
	Year      int64       `json:"year"      description:""`
	Month     uint        `json:"month"     description:""`
	Day       uint        `json:"day"       description:""`
	Category1 string      `json:"category1" description:""`
	Category2 string      `json:"category2" description:""`
	Tag       string      `json:"tag"       description:""`
	Event     string      `json:"event"     description:""`
	Summery   string      `json:"summery"   description:""`
	Status    uint        `json:"status"    description:""`
	About     uint        `json:"about"     description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
}
