// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FreeKeyVisitLog is the golang structure for table free_key_visit_log.
type FreeKeyVisitLog struct {
	Id        uint64      `json:"id"        description:""`
	Visit     uint64      `json:"visit"     description:""`
	Max       uint64      `json:"max"       description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
