// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Knowledge is the golang structure for table knowledge.
type Knowledge struct {
	Id        uint64      `json:"id"        description:""`
	Name      string      `json:"name"      description:""`
	Content   string      `json:"content"   description:""`
	Status    uint        `json:"status"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
