// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// NodeItem is the golang structure for table node_item.
type NodeItem struct {
	Id        int         `json:"id"        description:""`
	Cid       int         `json:"cid"       description:"分类id"`
	Name      string      `json:"name"      description:""`
	Url       string      `json:"url"       description:""`
	Desc      string      `json:"desc"      description:""`
	Sort      float64     `json:"sort"      description:""`
	Status    int         `json:"status"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
