// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Node is the golang structure for table node.
type Node struct {
	Id         int64       `json:"id"         description:""`
	Uid        int         `json:"uid"        description:""`
	Level      int         `json:"level"      description:""`
	Tag        string      `json:"tag"        description:""`
	MainThings string      `json:"mainThings" description:""`
	OtherInfo  string      `json:"otherInfo"  description:""`
	HappenDate string      `json:"happenDate" description:""`
	CreatedAt  *gtime.Time `json:"createdAt"  description:""`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:""`
}
