// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// NodeCategory is the golang structure for table node_category.
type NodeCategory struct {
	Id              int         `json:"id"              description:""`
	Name            string      `json:"name"            description:""`
	Icon            string      `json:"icon"            description:""`
	FontColor       string      `json:"fontColor"       description:""`
	BackgroundColor string      `json:"backgroundColor" description:""`
	Sort            float64     `json:"sort"            description:""`
	Status          int         `json:"status"          description:""`
	CreatedAt       *gtime.Time `json:"createdAt"       description:""`
	UpdatedAt       *gtime.Time `json:"updatedAt"       description:""`
}
