// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// QuestionCategory is the golang structure for table question_category.
type QuestionCategory struct {
	Id     uint64 `json:"id"     description:""`
	Name   string `json:"name"   description:""`
	Icon   string `json:"icon"   description:""`
	Desc   string `json:"desc"   description:""`
	Sort   uint   `json:"sort"   description:""`
	Num    uint   `json:"num"    description:"article num"`
	Status uint   `json:"status" description:""`
}
