// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Question is the golang structure for table question.
type Question struct {
	Id        uint64      `json:"id"        description:""`
	Question  string      `json:"question"  description:""`
	Category  string      `json:"category"  description:""`
	Desc      string      `json:"desc"      description:""`
	Icon      string      `json:"icon"      description:""`
	EnContent string      `json:"enContent" description:""`
	Visit     uint64      `json:"visit"     description:""`
	Status    uint        `json:"status"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
}
