// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Quotations is the golang structure for table quotations.
type Quotations struct {
	Id        uint64      `json:"id"        description:""`
	Book      string      `json:"book"      description:"书籍名称"`
	Writer    string      `json:"writer"    description:"作者名称"`
	Category  string      `json:"category"  description:"类型"`
	Content   string      `json:"content"   description:""`
	ContentEn string      `json:"contentEn" description:""`
	Like      uint64      `json:"like"      description:"喜欢的次数"`
	Status    uint        `json:"status"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
