// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ReadCategory is the golang structure for table read_category.
type ReadCategory struct {
	Id          int64       `json:"id"          description:""`
	Name        string      `json:"name"        description:""`
	Desc        string      `json:"desc"        description:""`
	Speak       string      `json:"speak"       description:""`
	Icon        string      `json:"icon"        description:""`
	Poster      string      `json:"poster"      description:""`
	TotalNum    uint        `json:"totalNum"    description:"文章数量"`
	Sort        uint        `json:"sort"        description:""`
	SubCategory string      `json:"subCategory" description:""`
	CreatedAt   *gtime.Time `json:"createdAt"   description:""`
}
