// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// RelationLink is the golang structure for table relation_link.
type RelationLink struct {
	Id        uint64      `json:"id"        description:""`
	Category  string      `json:"category"  description:""`
	Name      string      `json:"name"      description:""`
	Link      string      `json:"link"      description:""`
	Summery   string      `json:"summery"   description:""`
	Desc      string      `json:"desc"      description:""`
	Sort      int         `json:"sort"      description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
}
