// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// RoleApi is the golang structure for table role_api.
type RoleApi struct {
	Id  int `json:"id"  description:""`
	Rid int `json:"rid" description:""`
	Aid int `json:"aid" description:""`
}
