// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-22 10:15:49
// =================================================================================

package entity

// RoleMenu is the golang structure for table role_menu.
type RoleMenu struct {
	Id  int `json:"id"  description:""`
	Rid int `json:"rid" description:""`
	Mid int `json:"mid" description:""`
}
