// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Thing is the golang structure for table thing.
type Thing struct {
	Id        int64       `json:"id"        description:""`
	Name      string      `json:"name"      description:""`
	Type      int         `json:"type"      description:""`
	BeginTime *gtime.Time `json:"beginTime" description:""`
	Status    int         `json:"status"    description:"1"`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
