// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// TopUpCategory is the golang structure for table top_up_category.
type TopUpCategory struct {
	Id       uint64 `json:"id"       description:""`
	Title    string `json:"title"    description:""`
	SubTitle string `json:"subTitle" description:""`
	Type     uint   `json:"type"     description:""`
	Summary  string `json:"summary"  description:""`
	Desc     string `json:"desc"     description:""`
	Status   uint   `json:"status"   description:""`
}
