// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UUserStudyStatus is the golang structure for table u_user_study_status.
type UUserStudyStatus struct {
	Id                    uint64      `json:"id"                    description:""`
	Uid                   uint64      `json:"uid"                   description:""`
	WordNum               uint        `json:"wordNum"               description:"单词学习个数"`
	PersistInLearningDays uint        `json:"persistInLearningDays" description:"坚持学习天数"`
	LastLearningDate      *gtime.Time `json:"lastLearningDate"      description:"上次学习日期"`
	RedHardNum            uint        `json:"redHardNum"            description:"小红心个数"`
}
