// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        int         `json:"id"        description:""`
	Uname     string      `json:"uname"     description:""`
	Nickname  string      `json:"nickname"  description:""`
	Pwd       string      `json:"pwd"       description:""`
	Email     string      `json:"email"     description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
