// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"freekey-backend/internal/dao/internal"
)

// internalDictDao is internal type for wrapping internal DAO implements.
type internalDictDao = *internal.DictDao

// dictDao is the data access object for table s_dict.
// You can define custom methods on it to extend its functionality as you wish.
type dictDao struct {
	internalDictDao
}

var (
	// Dict is globally public accessible object for table s_dict operations.
	Dict = dictDao{
		internal.NewDictDao(),
	}
)

// Fill with you ideas below.
