// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"freekey-backend/internal/dao/internal"
)

// internalTopUpDao is internal type for wrapping internal DAO implements.
type internalTopUpDao = *internal.TopUpDao

// topUpDao is the data access object for table w_top_up.
// You can define custom methods on it to extend its functionality as you wish.
type topUpDao struct {
	internalTopUpDao
}

var (
	// TopUp is globally public accessible object for table w_top_up operations.
	TopUp = topUpDao{
		internal.NewTopUpDao(),
	}
)

// Fill with you ideas below.
