// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"freekey-backend/internal/dao/internal"
)

// internalUserLoginLogDao is internal type for wrapping internal DAO implements.
type internalUserLoginLogDao = *internal.UserLoginLogDao

// userLoginLogDao is the data access object for table u_user_login_log.
// You can define custom methods on it to extend its functionality as you wish.
type userLoginLogDao struct {
	internalUserLoginLogDao
}

var (
	// UserLoginLog is globally public accessible object for table u_user_login_log operations.
	UserLoginLog = userLoginLogDao{
		internal.NewUserLoginLogDao(),
	}
)

// Fill with you ideas below.
