// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"freekey-backend/internal/dao/internal"
)

// internalWalletStatisticsLogDao is internal type for wrapping internal DAO implements.
type internalWalletStatisticsLogDao = *internal.WalletStatisticsLogDao

// walletStatisticsLogDao is the data access object for table w_wallet_statistics_log.
// You can define custom methods on it to extend its functionality as you wish.
type walletStatisticsLogDao struct {
	internalWalletStatisticsLogDao
}

var (
	// WalletStatisticsLog is globally public accessible object for table w_wallet_statistics_log operations.
	WalletStatisticsLog = walletStatisticsLogDao{
		internal.NewWalletStatisticsLogDao(),
	}
)

// Fill with you ideas below.
