// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"freekey-backend/internal/dao/internal"
)

// internalWalletDao is internal type for wrapping internal DAO implements.
type internalWalletDao = *internal.WalletDao

// walletDao is the data access object for table w_wallet.
// You can define custom methods on it to extend its functionality as you wish.
type walletDao struct {
	internalWalletDao
}

var (
	// Wallet is globally public accessible object for table w_wallet operations.
	Wallet = walletDao{
		internal.NewWalletDao(),
	}
)

// Fill with you ideas below.
