// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// NodeItemDao is the data access object for table e_node_item.
type NodeItemDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns NodeItemColumns // columns contains all the column names of Table for convenient usage.
}

// NodeItemColumns defines and stores column names for table e_node_item.
type NodeItemColumns struct {
	Id        string //
	Cid       string // 分类id
	Name      string //
	Url       string //
	Desc      string //
	Sort      string //
	Status    string //
	CreatedAt string //
	UpdatedAt string //
}

//  nodeItemColumns holds the columns for table e_node_item.
var nodeItemColumns = NodeItemColumns{
	Id:        "id",
	Cid:       "cid",
	Name:      "name",
	Url:       "url",
	Desc:      "desc",
	Sort:      "sort",
	Status:    "status",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewNodeItemDao creates and returns a new DAO object for table data access.
func NewNodeItemDao() *NodeItemDao {
	return &NodeItemDao{
		group:   "default",
		table:   "e_node_item",
		columns: nodeItemColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *NodeItemDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *NodeItemDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *NodeItemDao) Columns() NodeItemColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *NodeItemDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *NodeItemDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *NodeItemDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
